### ISSUE TITLE
Painting to grid file and reading from a grid file

### ISSUE THREAD

**Issue by rainwoodman** [bccp/nbodykit#100]

**Comment by rainwoodman** [comment]
I am guessing we still need an example to finalize this?

**Comment by nickhand** [comment]
yeah I think so. Maybe we could incorporate it into a caching system (see #98)? Would be useful for reading cached painted fields

**Comment by rainwoodman** [comment]
I still want to finalize a 'format'. 

In the end I think we'd like to have a routine that decomposes (complex, ravelled_index) to a PM's complex buffer. 

I yet have to decide the format of the fastpm deltak field. I have a very mixed hate/love feeling on the current version. Take a look and what do you think?

https://github.com/rainwoodman/fastpm/blob/master/python/fastpm.py#L4

The biggest issue is the number of files is per rank and can get pretty bad on large runs. @aslanyan already suffer from this quite a bit - it takes several minutes to remove a folder.

**Comment by rainwoodman** [comment]
This is replaced by #221
