### ISSUE TITLE
shot noise removal on cross

### ISSUE THREAD

**Issue by nickhand** [bccp/nbodykit#14]
Shouldn't the shot noise be zero in the case of cross power spectrum rather than

shotnoise = pm.BoxSize ** 3 / (1.0 * Ntot1 * Ntot2) ** 0.5

**Comment by rainwoodman** [comment]
I just made it up so that it reduces to auto when data1=DATA2. do you know
if zero is correct ? Is there a reference? I remember Marcel said it was
complicated.

YU

**Comment by nickhand** [comment]
Well if we are considering the classic Poisson shot noise, which is usually what is subtracted out, then I think it should just be 1 / number density in the auto case and zero in the cross case, if the tracers are non-overlapping. It comes from the correlation of objects with themselves, which why it is important if the samples overlap at all. 

Section 2 of [this paper](http://mnras.oxfordjournals.org/content/400/2/851.full.pdf) has a good description (see eq 27). And section II of [this paper](http://arxiv.org/pdf/1305.2917.pdf) has the derivation of Poisson noise as "self-pairs" .

On a slightly related note, I was testing the cross-correlation code using different halo mass bins and noticed that the power was asymptoting to a constant at high k, like a Poisson noise term was present in the cross-correlation. It turns out this was due to a bug in the cross-power logic (see 58456f8 and 30ce79c). I am now finding that the cross-power spectra asymptote to zero in the high-k limit, as I expected.

Nick

**Comment by rainwoodman** [comment]
DId you commit the changes, if so let's close this.

**Comment by nickhand** [comment]
shot noise now zero in the cross case. closed by ad35bcc
