### ISSUE TITLE
formalizing DataSource columns

### ISSUE THREAD

**Issue by nickhand** [bccp/nbodykit#145]
I think we need to formalize the process by which we define readable columns for each DataSource. By default, all readers must return 'Position', but some also return 'Weight', 'Mass', etc + any columns that are named in the input data. And right now RaDecRedshift returns 'Position' as (ra, dec, z), which should really be named 'AngularPosition' or something, and also be able to return Ra, Dec, Redshift separately

Any good ideas on how to structure this, @rainwoodman ? 

We could have each DataSource define a list of preset columns, i.e., Position, Ra, Dec, Redshift, with an associated function that returns that column, given the data array

**Comment by rainwoodman** [comment]
Yes. We need a table somewhere to define the 'DataSource' protocol. 

We may start by surveying which algorithm requires which column and in what units.

**Comment by nickhand** [comment]
I was thinking about another Schema object and having the DataSource plugins declare the relevant Columns + 'aliases', where 'aliases' are the names of the columns in the file, but I couldn't find a solution I liked. 

I think we should first decide how to handle 'default' values for optional Columns, i.e., a lot of the time Weight is unity if not provided. 
   * We could just return 'None', and have the Painters set the defaults. 
   * I think we would still need some way to declare required Columns though, since I don't think it makes sense for a DataSource to return 'None' if 'Position' is asked for, etc

**Comment by rainwoodman** [comment]
We can insist that the consumer of the datasource will raise an error if it can't find a reasonable default value. So in the consumer we declare the default. e.g.

```
def paint(self, pm, datasource, ...)
    stream = datasource.read(['Position', 'Weight'])
    stream.set_default('Weight', 1)
    for Position, Weight in stream:
       ...
       ...
```
It still looks ugly, but we do want to reuse the code handling the default values..

**Comment by nickhand** [comment]
I think the introduction of the `DataStream` closes this, right?
