### ISSUE TITLE
cic crashes with mode='raise' and all particles within box

### ISSUE THREAD

**Issue by nickhand** [bccp/nbodykit#151]
if you set mode='raise' in ParticleMesh.paint and run any of the nbodykit power examples (outside of BianchiFFTPower), the paint will crash, despite all particles being in the box. There seems to be a possible issue in `_cic.py` where particles that are close to the outer box size are placed outside the box

see: 
https://github.com/rainwoodman/pmesh/blob/master/pmesh/_cic.py#L90

@rainwoodman, is this related to the fact that when using CIC, particles at the edges get distributed to edge +/- 1 cell, and need to be wrapped properly? If so, I would have thought this issue would also show up for particles near 0, but I don't see any evidence of that

**Comment by rainwoodman** [comment]
Yes... If I am trying to write to any location beyond the mesh, an error is raised. It shows up if the particle is close to 0 from the negative side.

I would think an error shall be raised because the total mass is not conserved in this case.

**Comment by nickhand** [comment]
so if I understand what's going on, there are really two separate cases: 

1) particles within the box say [0, L] that are near the edge and have mass assigned outside the bounds -- in the periodic case, it makes sense to wrap these and in the non-periodic case, the box should be big enough that this doesn't matter 
2) particles that are outside the [0, L] range initially, and then get wrapped into the box -- it probably makes sense to crash if we have these particles, but maybe the Painter/DataSource should enforce this?

**Comment by rainwoodman** [comment]
I agree with both cases -- if we agree on the semantics of pmesh then this is what we shall do.

**Comment by nickhand** [comment]
closing this after reaching the following conclusion:

pmesh will also wrap in nbodykit. In the specific cases where this is not the desired behavior, there should be explicit checks that the BoxSize is correct such that wrapping is irrelevant. This is the case for BianchiFFTPower, and the BoxSize check was added in #168. Basically in all other cases so far, wrapping is the right behavior.
