### ISSUE TITLE
Shall not write to .nbodykit 

### ISSUE THREAD

**Issue by rainwoodman** [bccp/nbodykit#188]
I find it strange the data files for testing are downloaded to ~/.nbodykit . Is there a good reason for doing so? 

If it is just testing data then wouldn't it make more sense to keep them in either a temporary directory or in the source code tree?

**Comment by nickhand** [comment]
I was mostly following the example of xarray, halotools, etc which seems to have it setup this way. I don't think there's any particularly good reason -- we can easily have it download to a directory in the source tree

**Comment by rainwoodman** [comment]
dot directories in home directory is not a place to store junk like this. In my opinion, it is surprising and impolite to keep uninvited data in a user's home without explicit consent. 

I am guessing the younger generation of unixers are more open to this? :)

Even if there is good reason to store these files in home, it should have been in 

$XDG_CACHE_HOME/nbodykit/testdata

that defaults to $HOME/.cache/nbodykit/testdata

**Comment by rainwoodman** [comment]
Yes I thought about this a bit more. Since we do not insist on deploying test data with the pip package, the data has to be downloaded when an end-user decides to run the tests. 

However, end user have no permission to write to the installed location of the package, thus the data has to be written somewhere else (not the package_data_dir)

If it is written to a temporary location, every time a test is ran it has to be downloaded again.
Therefore the simpliest choice is to download the data to home. 

But lets stay with the XDG standard and write to .cache/ instead of another .directory in $HOME.

**Comment by nickhand** [comment]
Okay this logic makes sense to me. 

I don't think XDG_CACHE_HOME is defined by default on OS X. I think part of the reason xarray defined their cache_dir variable with the `~` is the os.path.expanduser function which replaces it with $HOME. So I think we need to manually set it as ~/.cache/nbodykit or $HOME/.cache/nbodykit

**Comment by rainwoodman** [comment]
What about https://github.com/pypa/pip/blob/master/pip/utils/appdirs.py#L13
and skip the windows part?

This really should have been in the python standard library, IMO.

**Comment by rainwoodman** [comment]
Closed via efbc70d9c1bdae7bf838e2e240a41b1e3ca01aa8
