### ISSUE TITLE
Pick a format for the paper draft.

### ISSUE THREAD

**Issue by rainwoodman** [bccp/nbodykit#194]
I really liked the .rst format used in scipy_proceeding. But if we are for mnras we may need to patch their build system a bit to use that.

The good thing about rst is we can probably share quite a bit of text between the online document and the paper.

Is it worth the effort?

@nickhand

**Comment by nickhand** [comment]
That's a good point. Is there a reason for submitting to mnras vs say PRD or AAS? 

In any case, we'll need modify the build environment for any publication I would guess. I agree that it is a nice build environment for the paper...Do you have any idea how much work it would involve?

**Comment by rainwoodman** [comment]
The tools at scipy_proceeding lacks support to \citep. We need to add that. 
Otherwise seems to be pretty decently ready.

**Comment by rainwoodman** [comment]
No good reason not PRD or AAS.  There is also 'astronomy and computing'.

**Comment by nickhand** [comment]
AAS has been chosen
