### ISSUE TITLE
support grid interlacing 

### ISSUE THREAD

**Issue by nickhand** [bccp/nbodykit#196]
This would be a nice feature, especially to note in the paper in comparison to Roman's work

It seems like this would need to modify the ParticleMesh class to support this? @rainwoodman

**Comment by nickhand** [comment]
Maybe we want to take care of #118 while we are at it? Or maybe that should be closed?

**Comment by rainwoodman** [comment]
I never got the interlacing method working, so I don't really know the extent of the modification..

**Comment by rainwoodman** [comment]
But I think it is a good idea to finish 118 first if it blocks this. I recall there were some anormalies when I gave it a try. Forgot what it was though.

**Comment by nickhand** [comment]
Where does the new pmesh leave us on this? 

I think the most elegant way to do it is to change the simulation to grid transformation to add 0.5 so the second PM is offset. Is this doable? Do you want to add support directly to pmesh or use an Interlacing class in nbodykit?

**Comment by rainwoodman** [comment]
We can add a 'transform' argument to RealField.paint that allows one to
override the window.Affine object. BTW, when we do domain decomposition I
don't think we set the proper smoothing length yet for wider windows.

**Comment by rainwoodman** [comment]
I think the new pmesh provides the basics for doing the interlacing. If you have a reference code, I can look into porting that to pmesh.

**Comment by nickhand** [comment]
Great. I got the following code to work:

https://github.com/nickhand/nbodykit/blob/interlacing/nbodykit/interlacing.py

Should be easy to port over. Just need to do r2c on the two separate meshes, and then sum up the complex arrays, applying weights to the array from the shifted mesh

**Comment by rainwoodman** [comment]
There are problems:

It is possible we are missing some particles at the domain edge because of the 0.5 shifting.  So we need to run a different domain decomposition.

Then RealField.paint is cummulative. Thus we can't hack RealField.paint to do the FFT etc (because we may call .paint several times to obtain the final realfield).

Looks like the best place is not in pmesh, but as an InterlacedPainter plugin or an interlaced parameter of the DefaultPainter?

**Comment by rainwoodman** [comment]
Fixed.
