### ISSUE TITLE
BianchiFFTPower crashing on Edison

### ISSUE THREAD

**Issue by nickhand** [bccp/nbodykit#206]
I am suddenly seeing crashes on Edison running BianchiFFTPower. The error message is mysterious:

run: error: nid00018: tasks 0-23: Killed
srun: Terminating job step 1020397.4
srun: Force Terminated job step 1020397.4

It occurs when doing the Bianchi transfer function when (i, j, k) are nonzero:

https://github.com/bccp/nbodykit/blob/master/nbodykit/measurestats.py#L133

I think this is possibly memory-related. Thoughts, @rainwoodman ?

**Comment by rainwoodman** [comment]
I don't recall any recent changes regarding to memory usage though.
One possibility is to run the job interactively and launch with ddt to form a stack backtrace.

http://www.nersc.gov/users/software/performance-and-debugging-tools/ddt/

**Comment by nickhand** [comment]
I think what happened is that I've only tested BianchiFFTPower on Cori, and the same configuration that runs on Cori crashes on Edison due to memory limits
