### ISSUE TITLE
Pipeline / Filter

### ISSUE THREAD

**Issue by rainwoodman** [bccp/nbodykit#212]
A filter takes a source object and provides a data source interface

DataSource  -- source
DataSink -- Algorithm

Can we extend the config file such that it can specify a chain like this:

FastPMSim -> FOFFilter -> Zheng2013HOD -> BrightnessCut -> FFTPowerSpectrum

Without nesting deep?

**Comment by nickhand** [comment]
This is really interesting. We already have a few DataSources that just manipulate other data sources, so they are really just Filters. I am thinking of ShiftedObserver and ZhengHOD. Even the Selection Query is really just a filter

I could imagine having DataSource objects take a `filter` keyword that is a list of Filter plugins. And then behind the scenes, we are really returning a "filtered" DataSource

**Comment by rainwoodman** [comment]
We may want to use the plugin type to detect mismatched plugins. Because the connection may not always fit.. e.g.  (probably not a good example, but)

(Random, Data) -> FKPBinder - >FKPPower

FKPPower excepts a FKPBinder as input, not a generic DataSource.
