### ISSUE TITLE
completeness weights + FKP weights in Bianchi algorithm 

### ISSUE THREAD

**Issue by nickhand** [bccp/nbodykit#218]
We need to clarify want the "Weight" column used in FKP painter is. There are actually two different weights:

1. completeness weights can applied to the "data" or "randoms" field when painting
2. FKP weights are designed to weight the field difference w_fkp * [n_data - alpha * n_ran]

**Comment by rainwoodman** [comment]
Maybe adding a FKPWeight column?

**Comment by rainwoodman** [comment]
Is w_fkp a single number for the entire dataset or one number per data point?

**Comment by nickhand** [comment]
yeah I'll need to add an FKPWeight column -- each object has a different weight value. Lucas is testing out some code
