### ISSUE TITLE
remove auto assign?

### ISSUE THREAD

**Issue by nickhand** [bccp/nbodykit#226]
I think in theory this is nice, but some potentially downsides:

1. complicates things for users by hiding code
2. as we implement subclasses of plugin base classes and the code becomes more complicated, I think it will hinder development

I think we should still verify the schema for each class, but just not do the automatic setting of attributes. 

Also, if we want to have abstract attributes, I think we should add a check when during the schema verification process, rather than using the ``abc.abstractproperty`` decorator (which requires `property` setter/getter functions in the subclasses) 

Thoughts, @rainwoodman?

**Comment by rainwoodman** [comment]
Autoassign doesn't smell nice. +1 for removal. I thought it was introduced partially because we were injecting 'comm' and 'cosmology'. Do you still see a problem here?

**Comment by nickhand** [comment]
closed by #225
