### ISSUE TITLE
PaintGrid test case in for k-space input failing on python 2 (but not 3??)

### ISSUE THREAD

**Issue by nickhand** [bccp/nbodykit#229]
In PR #225, the test case for the Fourier grid fails on Travis. I have no idea why this is happening. Perhaps related to #228 ?

I cannot reproduce this on my Mac. All the tests pass just fine. I've deleted the Travis caches and re-run so that doesn't appear to be the issue.

**Comment by nickhand** [comment]
the TestGridK test is now working but the TestGrid case fails in #225. 

I think the reference output might be wrong? I fixed a bug where both TestGridK and TestGrid had the same class name, which means the TestGrid case was never actually run previously

The logging output looks reasonable to me, while the reference data looks like it wasn't renormalized

**Comment by rainwoodman** [comment]
Looks so to me too. I updated the reference result.

**Comment by nickhand** [comment]
#225 issues fixed; closed by fixes in pmesh and new reference result
