### ISSUE TITLE
master doesn't work on NERSC. 

### ISSUE THREAD

**Issue by rainwoodman** [bccp/nbodykit#230]
Even FOF fails with mysterious errors.

**Comment by rainwoodman** [comment]
Looks like the nbodykit-dep.tar.gz is missing python2.7 files.

**Comment by nickhand** [comment]
what machine is this?

**Comment by rainwoodman** [comment]
Edison.  It works if I make the bundles myself with bundle-pip. So seems like it is only the nersc integration that is broken.

**Comment by rainwoodman** [comment]
Could it be some errors in buliding python2.7 files are neglected? Where do you save the cron logs?

**Comment by nickhand** [comment]
Oh, I know what is wrong. I switched to python 3 on nersc and it's building with the python 3 environment and directory names

Do we need to build separate python 2 and 3 bundles (to get the untarred destination path right) ?

**Comment by nickhand** [comment]
Also, I just get the cron logs as emails. Do you want me to automatically forward them to you?

**Comment by rainwoodman** [comment]
What about saving the log in a text file together with the build?

I don't think we need seperate python 2 and 3 bundles, though I am not sure how you build both.. maybe we want to add a -u argument to bundle-pip?

**Comment by rainwoodman** [comment]
I mean build both into the same file.

**Comment by rainwoodman** [comment]
I mean 2.

**Comment by nickhand** [comment]
I think we should try to keep python 2 support for now. 

I think we should be able to build them into the same bundle in `nightly-build.sh`, doing module load/unload, and determining the right output directory (i.e, `./lib/python2.7/site-packages` vs `./lib/python3.5/site-packages`)

Does that seem reasonable?

**Comment by nickhand** [comment]
I'll take a look at this now

**Comment by nickhand** [comment]
is this the layout we would need to do multiple python versions: 

1. unload python; load python 2.7
2. install nbodykit, requirements into /lib/python2.7/site-packages
3. unload python; load python 3.5
2. install nbodykit, requirements into /lib/python3.5/site-packages

which can be bundled into the same tarball, but does requires installing two version of everything?

**Comment by rainwoodman** [comment]
Yes.  I think so.
