### ISSUE TITLE
Big fat datasource?

### ISSUE THREAD

**Issue by rainwoodman** [bccp/nbodykit#240]
Maybe we shall demand a datasource to provide three interfaces:
1. creates a dask array of particles hosted on this process for a given PM.
2. creates a RealField object for a given PM.
3. creates a ComplexField object for a given PM.

The the algorithms simply take the one it wants and do with it. How does this sound?

This in some sense captures the Field objects.

It can be an extension point or not. We provide a NBKitDataSource object that uses the StackFile for 1,  and merge in the DefaultPainter for 2 and 3.

**Comment by nickhand** [comment]
Hmm, I think I like it....it makes a lot of sense. 

The algorithms that don't need real,complex, etc wouldn't use it but the API to use it would still be there

**Comment by rainwoodman** [comment]
OK. I'll massage MultiFile towards that.

**Comment by rainwoodman** [comment]
done in v2
