### ISSUE TITLE
negative mu in PeriodicBox

### ISSUE THREAD

**Issue by rainwoodman** [bccp/nbodykit#257]
There is no way to do negative mu in PeriodicBox thus the dipole is always zero.
We can fix this by adding an argument to FFTPower and FFTCorrelation, `negativemu` or some better looking names, to say we are using 2 * Nmu + 1 mu bins, from -1 to 1. instead of from 0 to 1.

**Comment by rainwoodman** [comment]
@nickhand do you have a better name for the argument? any complications?

**Comment by nickhand** [comment]
I think `negativemu` keeps things the simplest., and can't really think of a better name. The alternative would be to generalize and allow arbitrary `mu` binning via a `mulimits` argument with [0, 1] the default but I think that might overly complicates things. What do you think?

**Comment by rainwoodman** [comment]
OK this doesn't make any sense.

**Comment by rainwoodman** [comment]
We never find any negative mu because the field is hermitian.
