### ISSUE TITLE
crashes on Edison in batch mode

### ISSUE THREAD

**Issue by nickhand** [bccp/nbodykit#260]
possibly related to numpy dtype bugs -- see #259

**Comment by nickhand** [comment]
I've confirmed that the issue is related to the new pmesh interface introduced in #223  (I get the error using 14fe8b4 but not on 2f5b25a)

@rainwoodman , perhaps this is due to some numpy dtype issues in the new interface of pmesh?

**Comment by rainwoodman** [comment]
I don't see anything problematic there. all calls to empty looked fine.

**Comment by rainwoodman** [comment]
A stack trace from ddt may be able to give us some information. Do you have a 'case'?

**Comment by nickhand** [comment]
due to memory leak in pmesh. closed via [789982cd](https://github.com/rainwoodman/pmesh/commit/789982cd) in v0.0.19
