### ISSUE TITLE
CSV file broken with updates to dask

### ISSUE THREAD

**Issue by nickhand** [bccp/nbodykit#269]
I never removed a dependency  on a function (`dask.bytes.local.read_bytes`) in the dask library that has now been removed. Will implement the function in nbodykit to remove the dependency. 

Technically, this affects master and v2.0, although people really shouldn't been using the ``io`` library yet. This affects the stable branch only if people try to read using CSVFile. 

@rainwoodman, I am thinking I should just push a fix to v2.0 branch?

**Comment by rainwoodman** [comment]
Why are we even using dask.bytes.local.read_bytes? I am thinking of rewriting CSVFile with caching and 'partition' fully handled by the file object, not dask. (IO still done by dask upon request).

**Comment by nickhand** [comment]
`dask.bytes.local.read_bytes` is just a simple wrapper around `dask.utils.read_block`, which appears to be the more intrinsic function. It handles reading bytes of a certain size from a file, making sure the block ends on a certain delimiter. This is how the CSV file gets partitioned, using the newline character

**Comment by nickhand** [comment]
But re-writing might be a good idea here, especially with some sort of caching. Although, I think the byte-partitioning would be very similar to what dask is doing. But I think we could do the partitioning in nbodykit and do the reading using `pandas.read_csv` which removes the `compute` call

**Comment by rainwoodman** [comment]
Can't we just return dataframe[start:stop:step]  or alike in read?

**Comment by nickhand** [comment]
Do you mean without partitions? At the moment, CSVFile is basically a FileStack of "read_csv" calls, with the idea being that if you partition, you drastically cut down loading time near the end of the file

**Comment by rainwoodman** [comment]
I don't understand. If I request a slice from dask.DataFrame (which has been partitioned by the blocksize attribute), doesn't dask automagically seek to the intersection partition and parse only those partitions?

**Comment by nickhand** [comment]
fixed in #272
