### ISSUE TITLE
mu = 0 has a lot more power

### ISSUE THREAD

**Issue by rainwoodman** [bccp/nbodykit#270]
in v2 mu=0 gives unrealistically large power. I tried very hard and didn't find anything obviously wrong. @nickhand

**Comment by nickhand** [comment]
what was the use case?

**Comment by rainwoodman** [comment]
Looks like it is the csv reader. I tested zeldovich it is OK. I am trying to read some BOSS mocks for Yin.

**Comment by nickhand** [comment]
due to lack of `hold=True` in painter. fixed in v2.0
