### ISSUE TITLE
Unit tests for the cosmology class. 

### ISSUE THREAD

**Issue by rainwoodman** [bccp/nbodykit#285]
I will take care of this.

I also would like to add interface to call these functions from scaling factor. Not sure how yet.

**Comment by nickhand** [comment]
Okay. I don't love the handling of attributes/functions from the underlying astropy "engine", but it does work and I'm not sure there's a better way. I think we do need to at least add a test that orthogonal parameters that get added to the dict itself during construction don't conflict with the astropy attributes

**Comment by rainwoodman** [comment]
I am more concerned about the growth rate functions.
