### ISSUE TITLE
calling run() inside algorithm __init__

### ISSUE THREAD

**Issue by nickhand** [bccp/nbodykit#292]
I didn't realize that FFTPower was doing this

https://github.com/bccp/nbodykit/blob/v2.0/nbodykit/algorithms/fftpower.py#L133

@rainwoodman, is this the syntax we want? I agree that the extra run() call is basically pointless and this eliminates a line, but it is tricky for debugging if we forget to put it in...

**Comment by rainwoodman** [comment]
I am treating these 'algorithms' as function calls that returns an *immutable* bject that contains their output. I think this narrative fits better into 'scripting with a programming language'..

But then in LPTParticles the result is not really immutable (setting redshift changes the result).

**Comment by nickhand** [comment]
okay closing this
