### ISSUE TITLE
add python 3.6 to travis

### ISSUE THREAD

**Issue by nickhand** [bccp/nbodykit#310]

**Comment by rainwoodman** [comment]
conda-forge had issue with 3.6 that's why a lot of receipts carried over were missing 3.6. Once we green 3.6 on travis we can start building for 3.6 on anaconda.

**Comment by nickhand** [comment]
the python 3.6 builds and Travis tests look good. There are some unrelated mpi4py import warnings but everything passed. Closing via #313
