### ISSUE TITLE
sort out dependencies and NERSC builds

### ISSUE THREAD

**Issue by nickhand** [bccp/nbodykit#311]
It seems like we have conflicting information in `install_requires` and `requirements.txt`? We should decide how we want to handle "optional" dependencies like halotools, cachey, and h5py which are only needed for some classes. 

I think the only use of `requirements.txt` at the moment is the NERSC builds. We could maintain a base anaconda + nbodykit conda environment on NERSC and then you would only need to activate that environment? It seems like that would simplify a lot of things with respect to the nightly builds. 

I am leaning towards not having any "optional" dependencies. It adds up to quite a bit of dependencies, but ensures the users have full functionality. 

If we wanted to have "optional" dependencies, it seems like the proper way to do that is:

https://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies

See how this is done in practice, i.e., here: https://github.com/getnikola/nikola/commit/836e395ad5dc82b27a9b0ebd03efca29483bbdc7

**Comment by rainwoodman** [comment]
nbodykit[base] .vs. nbodykit[full]?

**Comment by nickhand** [comment]
yes it would be something like that...And then the conda builds we could just install the "full" version I think

**Comment by rainwoodman** [comment]
That's nice. I'll also change fastpm-python to have a fastpm[nbodykit] feature.

**Comment by nickhand** [comment]
okay, the new setup is now working. load nbodykit environment with:
```bash
source /usr/common/contrib/bccp/conda-activate.sh $PYTHON
```
where `PYTHON` can be 2.7, 3.5, or 3.6

Nightly cron job is set up on edison and cori

Closing now.
