### ISSUE TITLE
Nersc script in bccp/nbodykit is broken.

### ISSUE THREAD

**Issue by rainwoodman** [bccp/nbodykit#314]
The branching in != dev is missing an assignment of `$version=$ver`. I added a script a.sh on edison for a quick fix for Jerry.

Shall we actually revert these scripts to the older ones?

**Comment by nickhand** [comment]
Is Jerry using v0.1.x on NERSC? Is there any one else using v0.1?

The v0.1.x activate scripts can only load 0.2 and HEAD of master so it's probably better to just commit the fix to master for now.

**Comment by rainwoodman** [comment]
Yes. He is. Presumable @marcel-sl as well; and I have a bunch of legacy scripts that would likely to run from time to time.

`
The v0.1.x activate scripts can only load 0.2 and HEAD of master so it's probably better to just commit the fix to master for now.
`

What do you mean? This sounds like a strange situation.

I would say we 

- revert the scripts in contrib/bccp/nbodykit to the 0.1.x branch, such that it never loads 0.2.

- To use the current version of nbodykit (0.2), we use `bccp/activate-conda.sh`. If a particular version  (e.g. 0.1.9)  is expected bcast-pip it manually after enabling the bccp conda env.

**Comment by nickhand** [comment]
Okay, sure I think we can do that. We just need to pin the v0.1.x version to install <0.2. We can just remove the "latest" option such that it only installs "stable" (the default option). If "latest" is selected, we'll just point them to the new syntax.

**Comment by mschmittfull** [comment]
I made a private fork of v0.1 a while ago and I'm still using this on nersc sometimes. Let me know if I should change anything to use that. At some point I'll try to switch to v0.2.

**Comment by nickhand** [comment]
Thanks, @mschmittfull! We should have some examples, better documentation soon to make the switch easier, but the goal is to not break any legacy stuff.

@rainwoodman -- I think I'll just add the `version=$ver` to the existing script. Deepthi is using the "dev" version of this and hasn't yet switched to the new syntax. This also maintains the behavior of the  original command so everything should be fine. I'll double-check all options of the script are working...

**Comment by rainwoodman** [comment]
Sounds like a good plan!

**Comment by mschmittfull** [comment]
Thanks, sounds great!
