### ISSUE TITLE
add selection in 3pt algorithm

### ISSUE THREAD

**Issue by nickhand** [bccp/nbodykit#318]
forgot to add selection support here

I am becoming more convinced from talking to new users that the ability to slice sources with a boolean array directly would be very powerful  and more intuitive....thoughts @rainwoodman?

**Comment by rainwoodman** [comment]
I agree. Propagating the type of source will be nasty -- maybe we don't need that. We just need a SlicedSource type where all attrs are copied?

**Comment by nickhand** [comment]
closed by #357
