### ISSUE TITLE
LogNormalCatalog depends on number of ranks

### ISSUE THREAD

**Issue by nickhand** [bccp/nbodykit#358]
The number of objects in LogNormalCatalog depends on the number of ranks used, even when setting the seed. I thought we had confirmed this worked properly in the past...so this must be a new bug? 

It looks to me like the "delta_k" array is generated properly via the `generate_whitenoise` function, regardless of the number of ranks. The ``c2r`` operation seems to introduce some slight differences in the ``delta`` array, leading to issues when poisson sample it. 

Thoughts on what might be going on, @rainwoodman ?

**Comment by rainwoodman** [comment]
I noticed this and assumed it was the bad sampling. c2r shouldn't give slight difference parallel or not (up to numerical precision) -- unless the whitenoise is not properly set hermitian -- how big a difference did you see?

**Comment by nickhand** [comment]
I don't think it's the Poisson sampling -- the root rank does that sampling and broadcasts to avoid this issue. The differences are at the ~1e-3 level in the delta array for the the short example I was looking at

**Comment by rainwoodman** [comment]
Could you paste the short example so that I have something to start with?

**Comment by nickhand** [comment]
```python
from pmesh.pm import ParticleMesh
import numpy

BoxSize = 512
Nmesh = 128
pm = ParticleMesh(BoxSize=BoxSize, Nmesh=numpy.ones(3)*Nmesh, dtype='f4')
comm = pm.comm

delta_k = pm.generate_whitenoise(seed=42, mode='complex', unitary=False)
csum = comm.allreduce(delta_k.value.sum())
if comm.rank == 0:
    print("delta_k csum = ", csum)

delta = delta_k.c2r()
csum = delta.csum()
if comm.rank == 0:
    print("delta csum = ", csum)
```

When run with 1 process, I get: 

```
delta_k csum =  (-1070.84+242.637j)
delta csum =  -0.25
```

and with 4 processes: 

```
delta_k csum =  (-1070.84+242.637j)
delta csum =  -0.1875
```

**Comment by rainwoodman** [comment]
I can confirm this and make sense of it.

The difference is tiny and well within numerical error. We know parallel FFT and sequential FFT differ up to numerical precision * some factor.

The mean of the field is zero, so csum is close to one. If you look at the code csum doesn't promote the type of variable during summation, so all you get is an round off error.

If you replace csum with cnorm, which doesn't adds to zero, then you see good agreement.

When you seed the Poisson sampling, what about first rounding off the numbers to some digits?

**Comment by nickhand** [comment]
Rounding doesn't seem to work well enough. There are always a few cells with different values so the total number comes out slightly different. I am not sure it's worth the effort of trying to fix. Is there anywhere where this is really a problem?

**Comment by rainwoodman** [comment]
So far it only created a few surprises.  No real problem yet.

**Comment by nickhand** [comment]
Having tried all of the "simple" solutions, I am going to close this for now, until it creates a real issue for us.
