### ISSUE TITLE
CSVFileCatalog missing last row.

### ISSUE THREAD

**Issue by rainwoodman** [bccp/nbodykit#359]
A few weeks ago, we noticed reading a CSV file always misses the last row, at least when the file is very short, e.g. having only three rows. Filing before I forget.

**Comment by nickhand** [comment]
Do you have an example file?

**Comment by rainwoodman** [comment]
This should work:
```
0 0 0 0
1 1 1 1
2 2 2 2
```
Whether the last line has a new line may be relevant.

**Comment by rainwoodman** [comment]
![screenshot from 2017-07-05 11-36-50](https://user-images.githubusercontent.com/138060/27879378-44d048b4-6176-11e7-8621-d37a32411ff1.png)

**Comment by nickhand** [comment]
yeah this is because of the lack of a newline. I'll push a fix and add a test
