### ISSUE TITLE
Poor quality of neutrino energy density

### ISSUE THREAD

**Issue by rainwoodman** [bccp/nbodykit#363]
We currently use the neutrino energy density from astropy, which uses the Komatsu fit in the Planck paper. This has a few drawbacks

- The energy density is different from direct calculation from the true distribution function. The figure below shows the difference in the total matter + radiation density compared to CLASS (via classylss.binding). At z=0 the neutrino mass density differ by 0.5%. as a result, classylss and nbodykit disagree when there is neutrino.
 
![index](https://user-images.githubusercontent.com/138060/28245339-1f157766-69b9-11e7-9486-600965d29a0e.png)

- There is no way to tell the split between non-relativistic and relativistic component of massive neutrino and the massless neutrino. (The split between massless and massive is a technical issue, but the split between nr and r components is due to lack of a fit for the derivative of the partition function).

- This affects the formula of efunc_prime, where we currently used the derivative of the fitting formula. It should have been constructed from the energy density instead, and I am not sure if we really want to take the derivative against the distribution function (there is a k dependency).

- The non-relativestic portion of the massive neutrino is used in the 2/3 Fluid approximation, which is useful in a bunch of scenarios for setting up N-body simulations that are aware of neutrinos. We currently have to invoke classylss.binding to obtain this and E and E' for the solver. 

There are a few ways of getting around this:

- since classylss.binding works, we can switch to a new cosmology engine with CLASS? We get linear theory power spectrum and transfer functions for free then. 

- We can fix the neutrino related quantities in nbodykit to use the distribution function, with the hope to eventually merge the fix to astropy, such that CLASS and astropy agrees. There might be resistance from Astropy though.

**Comment by nickhand** [comment]
I think I like option #1 better but could be persuaded either way. What do you think? 

Either way, we should start to think about what remaining features we want in the version described in the paper...I'm starting work on docs + the paper this week...

**Comment by rainwoodman** [comment]
My researvation about path 1 is how do we survive between the conflicting astropy notation and class notation.

**Comment by rainwoodman** [comment]
Let's move this to https://github.com/bccp/nbodykit/pull/365 .
