### ISSUE TITLE
from nbodykit import style

### ISSUE THREAD

**Issue by lessiar** [bccp/nbodykit#374]
Hello.
I installed nbodykit using anaconda on my laptop (using Ubuntu bash on Windows 10) and a cluster, and on both cases I have problems using the example notebooks. In each case, I get an error with 

>> from nbodykit import style
>> ImportError: cannot import name 'style'

And I can't follow the notebooks because of it. 
On both cases I am using Anaconda 3 and Python 3.6.2.

I was wondering if there was an issue with "style" or if I'm doing anything wrong.

Thanks in advance!

**Comment by nickhand** [comment]
Nope, you aren't doing anything wrong. This is an issue with the docs being a bit ahead of the latest release of the code on Anaconda (you should have v0.2.4) and the docs were built with 0.2.5. We can tag a new release shortly which should fix this. In the meantime, you can comment out the "from nbodykit import style" and the notebooks should work.

**Comment by lessiar** [comment]
Oh, I see! Thanks a lot. ;)
