### ISSUE TITLE
CatalogCopy better named to CatalogRef?

### ISSUE THREAD

**Issue by rainwoodman** [bccp/nbodykit#377]

**Comment by nickhand** [comment]
Yes, I think I like this name better...

**Comment by nickhand** [comment]
The problem is that it's not always a subset, like when we are concatenating multiple source together. It's really just a Catalog where the columns are passed in as kwargs

**Comment by rainwoodman** [comment]
Maybe we don't need a new class? It's just a special method of Catalog?

**Comment by rainwoodman** [comment]
I am also a bit unsure the relation between this and an ArrayCatalog, which takes an dictionary as an input but does a bunch more (seemingly unnecessary) work.

**Comment by nickhand** [comment]
I think the difference is that the size is known beforehand for CatalogCopy/Ref but not for ArrayCatalog . But we could remove CatalogCopy in favor of a class method of CatalogSource -- it makes more sense to have "CatalogSource" then showing up in all of the log statements

**Comment by nickhand** [comment]
I guess we'll need to get rid of the abstract property tag on ``size`` for this to work?

**Comment by rainwoodman** [comment]
Yes - I did that in #390.

**Comment by nickhand** [comment]
closed via #390
