### ISSUE TITLE
dask.array no longer allow attaching attributes. 

### ISSUE THREAD

**Issue by rainwoodman** [bccp/nbodykit#380]
in `catalog.py we attach attrs the the column dask array. This is no longer supported in recent dask. The Array class is now slotted. 

Combining this with the need of a customized compute and poor representation, I think we shall add a subclass of dask array for the columns. I will file a PR around today. Currently everything is broken due to this.

**Comment by nickhand** [comment]
Sounds good, thanks. I am working on the pyHPC all day today...

**Comment by nickhand** [comment]
We will need to tag a new release or enforce the proper dask version on NERSC

**Comment by rainwoodman** [comment]
I say go with a new release. If it's messed up we will just fix and tag a new one.. How do you enforce a proper dask version on NERSC?

**Comment by nickhand** [comment]
yes I think we should tag a new release and update the change log. And then we can merge the new cosmology stuff in to the following release. 

We have a "conda update --all" in our nightly build script that we would need to modify...the new release is cleaner
