### ISSUE TITLE
Clone is buggy, and convoluted logic in argument handling in classylss cosmology

### ISSUE THREAD

**Issue by rainwoodman** [bccp/nbodykit#382]

**Comment by rainwoodman** [comment]
- The temporary cosmo object created during clone is quite hard to grab. I think we are really just looking at 'equivalent classes' of arguments, and drop the ones in the old args if new ones are given.
- the semantics of cosmo.args was not clear. I think we can define it as the set of arguments to sufficiently decide a 'Cosmology' object. Then there is no need for an kwargs argument. 

I am working on a PR for this.

**Comment by nickhand** [comment]
Yes I was working towards those goals I think. The args are supposed to hold named arguments and kwargs hold everything else. I think the confusion might be a remnant of when I had the "extra" dict as a keyword

**Comment by nickhand** [comment]
closed by #386
