### ISSUE TITLE
BOSS weighting?

### ISSUE THREAD

**Issue by fbeutler** [bccp/nbodykit#412]
Hi 
I just went through the BOSS DR12 tutorial... great stuff... just one question. You calculate the data systematic weight as 

data['WEIGHT_SYSTOT'] * (data['WEIGHT_NOZ'] + data['WEIGHT_CP'] - 1.0)

but isn't WEIGHT_SYSTOT exactly defined like that? If you want to calculate the systematic weight from scratch wouldn't it be 

data['WEIGHT_STAR'] * (data['WEIGHT_NOZ'] + data['WEIGHT_CP'] - 1.0)

? I am talking about this tutorial...

http://nbodykit.readthedocs.io/en/latest/cookbook/boss-dr12-data.html

cheers
fl

**Comment by nickhand** [comment]
I believe it follows the discussion in https://arxiv.org/abs/1509.06529 where WEIGHT_SYSTOT is defined as the product of WEIGHT_STAR x WEIGHT_SEEING
