### ISSUE TITLE
Newtonian gauge cosmology transfer function is broken

### ISSUE THREAD

**Issue by energy-berkeley** [bccp/nbodykit#413]
I checked with direct calling class, transfer function from class for synchronous gauge and newtonian gauge should be different. However, Planck15.clone(m_ncdm = 0.6, gauge='newtonian') would give exactly the same transfer function as synchronous gauge.

**Comment by rainwoodman** [comment]
Did you figure it our? there is an attributed called `parameter_file` that has the plain text version of the parameter file passed into CLASS -- can you take a look if that looked reasonble?

**Comment by energy-berkeley** [comment]
That problem was solved, just a typo in paramter. Within horizon the two deltas agrees, above horizon they disagree.

**Comment by rainwoodman** [comment]
Great. If you sense it can be a common error, then it is probably useful to add it to the documentation. (I sense it is not a common error)
