### ISSUE TITLE
question: using FOF Class on observed (not simulated) galaxy catalog

### ISSUE THREAD

**Issue by moustakas** [bccp/nbodykit#417]
I've just started using the awesome `nbodykit` tools -- thanks for writing them!

I'd like to use the `nbodykit.algorithms.fof.FOF` class to generate a group catalog from an observed sample of galaxies with just RA,Dec coordinates using a simple angular linking length.  I'm doing something like
```
from nbodykit.transform import SkyToUnitSphere
from nbodykit.source.catalog import FITSCatalog
from nbodykit.algorithms.fof import FOF

cat = FITSCatalog('mycatalog.fits')
cat['Position'] = SkyToUnitSphere(cat['RA'], cat['DEC'], degrees=True)
fof = FOF(cat, linking_length=0.05, nmin=1, absolute=True)
```
However, this crashes with the message
```
ValueError: cannot compute FOF clustering of source without 'BoxSize' in ``attrs`` dict
```
Is what I'm trying to do possible?

**Comment by rainwoodman** [comment]
FOF requires you to embed the data to a periodic box -- in this case you can probably add
to your script
```
cat.attrs['BoxSize'] = 4.0
cat['Position'] += 2.0
```

Which will shift the points to the center of the box of size 4.0 -- Could you see if this works? We shall add a non-periodic option to FOF that uses automatically computed boxsizes. I'll file a PR to add this feature.

**Comment by rainwoodman** [comment]
Feature is in (periodic == False) -- workaround above no longer needed. Closing. Thanks!
