### ISSUE TITLE
astropy methods for cosmology class

### ISSUE THREAD

**Issue by fbeutler** [bccp/nbodykit#422]
I am trying to calculate the Hubble parameter with the cosmology class, but it does not seem to exist? The angular diameter distance works file

    print("cosmo.H(0.5) = ", cosmo.H(0.5))
  File "/Users/xflorian/anaconda/envs/nbodykit-env/lib/python3.6/site-packages/nbodykit/cosmology/cosmology.py", line 221, in __getattr__
    raise AttributeError("Attribute `%s` not found in any of the delegate objects" % name)
AttributeError: Attribute `H` not found in any of the delegate objects

**Comment by rainwoodman** [comment]
Most of the astropy methods are removed as we change to CLASS set of function names:
```
In [3]: from nbodykit.cosmology import Planck15

In [4]: Planck15.hubble_function?
Docstring:
Background.hubble_function(self, z)

The Hubble function in CLASS units. Users should use :func:`efunc`
instead.
Type:      builtin_function_or_method
```

Tab-completion shows these names but currently they are not in the documentation of classylss or nbodykit, unfortunately.

**Comment by rainwoodman** [comment]
As, as noted in the docstring, you probably want to use Planck15.efunc and multiply with Planck15.H0 (in Mpc/h units) instead.

**Comment by rainwoodman** [comment]
Temporary documentation of the available methods is listed at http://rainwoodman.github.io/classylss.

**Comment by fbeutler** [comment]
thanks Yu

**Comment by rainwoodman** [comment]
The documentation is added. Check it out! http://nbodykit.readthedocs.io/en/latest/api/api.html#cosmology-nbodykit-cosmology
