### ISSUE TITLE
allow some columns to not be saved to disk / cleanup hard columns vs defaults

### ISSUE THREAD

**Issue by nickhand** [bccp/nbodykit#431]
moving the discussion from #427 here. We would like to be able to save certain columns to disk, i.e., do not save default columns to disk. 

This will likely involve a clean up of the "hardcolumn" syntax

**Comment by nickhand** [comment]
@rainwoodman We should be able to just create a "defaults" list (creating from something like a "defaultcolumn" decorator) such that the logic in getattr is 1) overrides, 2) hard columns, 3) defaults, 4) fail. And then by default do not save defaults?

**Comment by rainwoodman** [comment]
Perhaps another way is to get rid of Weight, Value and Selection columns alltogether. to_mesh is the only place these are used, and we already have keywords to choose which column to use. We can simply change the default to None and generate them on the fly during to_mesh.

**Comment by rainwoodman** [comment]
Then all columns listed in .column contain valuable information and shall be saved.

**Comment by nickhand** [comment]
My only worry there is that we've operated under the assumption that those columns are there in catalog objects. We would likely have to re-work some non-obvious things

**Comment by rainwoodman** [comment]
Yes. It will require special cases in all algorithms. They path is not worthy. Let's go with 'defaults'.

What to do about the 'Position' column in HodCatalog? Does it go to disk or not? If we have an answer on that I think we can pin down the desired behavior.

**Comment by nickhand** [comment]
I think it would go to disk. I would say only Selection, Weight, Value don't need to be saved

**Comment by rainwoodman** [comment]
So we shall have a special Column Decorator that claims a column shall not be stored -- which means the catalog base class need a dictionary to keep track of this information.

**Comment by nickhand** [comment]
Wait, the save() function of catalogs takes a "columns" argument, so this isn't actually an issue I think (unless I am missing something)

**Comment by rainwoodman** [comment]
It is an issue because the default behavior is not very good - it writes everything, including columns that we don't want (selection, weight, value)

**Comment by nickhand** [comment]
Ok I think understand...you are saying the current API encourages people to pass in "cat.columns" as the "columns" argument, which still saves the defaults. So we just need to check if any of the columns are defaults and ignore them.

**Comment by rainwoodman** [comment]
Or provide a non-default attribute (cat.usefulcolumns? I am out of good names) here that can be used here.
