### ISSUE TITLE
error after running "from nbodykit.lab import *"

### ISSUE THREAD

**Issue by cosmonomad** [bccp/nbodykit#455]
Hi there, 

I followed the instruction of installation with conda in my MacPro with macOS 10.11 without any error. But when I imported nbodykit.lab, I got a long message as below and was kicked out. 
It is likely related openmpi. Could you help me deal with this issue? 

dyld: lazy symbol binding failed: Symbol not found: _clock_gettime
  Referenced from: /Users/myname/anaconda/envs/nbodykit-env/lib/libopen-pal.40.dylib
  Expected in: flat namespace

dyld: Symbol not found: _clock_gettime
  Referenced from: /Users/myname/anaconda/envs/nbodykit-env/lib/libopen-pal.40.dylib
  Expected in: flat namespace

ORTE_ERROR_LOG: Unable to start a daemon on the local node in file ess_singleton_module.c at line 532
ORTE_ERROR_LOG: Unable to start a daemon on the local node in file ess_singleton_module.c at line 166

It looks like orte_init failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during orte_init; some of which are due to configuration or
environment problems.  This failure appears to be an internal failure;
here's some additional information (which may only be relevant to an
Open MPI developer):

  orte_ess_init failed
  --> Returned value Unable to start a daemon on the local node (-127) instead of ORTE_SUCCESS

It looks like MPI_INIT failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during MPI_INIT; some of which are due to configuration or environment
problems.  This failure appears to be an internal failure; here's some
additional information (which may only be relevant to an Open MPI
developer):

  ompi_mpi_init: ompi_rte_init failed
  --> Returned "Unable to start a daemon on the local node" (-127) instead of "Success" (0)

*** An error occurred in MPI_Init_thread
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
[is-m-00030:33758] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!

**Comment by rainwoodman** [comment]
The conda channel binary was built on a OSX 10.12, Xcode 8.3.3 (https://docs.travis-ci.com/user/reference/osx/#OS-X-Version), which has the function _clock_gettime. It appears your system is a bit older than that.

To fix the issue, I will rebuild the OSX packages with older version (OS X 10.10, Xcode 6.4). 
I'll let you know after the packages are rebuilt (it takes one or two days to get through the queue) -- would you be able to test then?

**Comment by cosmonomad** [comment]
My Xcode version is 8.2.1 on OS X 10.11.

**Comment by rainwoodman** [comment]
Could you take a look if the current version of binaries work on your Mac? We should have switched to lower versions of xcode already.

**Comment by cosmonomad** [comment]
Unfortunately, it did work for me. I have the same error.

**Comment by cosmonomad** [comment]
The version is 0.3.0-py27_3.

**Comment by rainwoodman** [comment]
Could you post me the entire output of `conda list`? The problem is probably one of the dependency packages that needs to be compiled; therefore just knowning 0.3.0-py27_3 isn't going to help.

**Comment by cosmonomad** [comment]
# Name                    Version                   Build  Channel
appnope                   0.1.0            py27hb466136_0
asn1crypto                0.24.0                   py27_0
astropy                   2.0.3            py27h1de35cc_0
attrs                     17.3.0           py27h04bc18c_0
backports                 1.0              py27hb4f9756_1
backports.functools_lru_cache 1.4              py27h2aca819_1
backports.shutil_get_terminal_size 1.0.0            py27hc9115de_2
backports_abc             0.5              py27h6972548_0
beautifulsoup4            4.6.0            py27h9416283_1
bigfile                   0.1.39           py27ha280d60_3    bccp
bokeh                     0.12.13          py27h5233db4_0
bzip2                     1.0.6                h649919c_2
ca-certificates           2017.08.26           ha1e5d58_0
cachey                    0.1.1            py27h1deb884_0    bccp
certifi                   2018.1.18                py27_0
cffi                      1.11.2           py27h21b8a49_0
chardet                   3.0.4            py27h2842e91_1
classylss                 0.2.8            py27he53cf42_5    bccp
click                     6.7              py27h2b86a94_0
cloudpickle               0.5.2            py27he962bb2_0
corrfunc                  2.0.0            py27h54ddd09_2    bccp
coverage                  4.4.2            py27hf37a882_0
cryptography              2.1.4            py27hdbc5e8f_0
cycler                    0.10.0           py27hfc73c78_0
cython                    0.27.3           py27h6429b90_0
dask                      0.16.1                   py27_0
dask-core                 0.16.1                   py27_0
decorator                 4.1.2            py27h9f877ea_0
distributed               1.20.2                   py27_0
enum34                    1.1.6            py27hf475452_1
fastcache                 1.0.2            py27hc4635c7_0
fitsio                    0.9.11           py27h4100e07_3    bccp
freetype                  2.8                  h12048fb_1
funcsigs                  1.0.2            py27hb9f6266_0
functools32               3.2.3.2          py27h8ceab06_1
future                    0.16.0                   py27_1
futures                   3.2.0            py27h1b80678_0
gmp                       6.1.2                hb37e062_1
gmpy2                     2.0.8            py27h4bc979a_2
gsl                       2.2.1                h002c638_3
h5py                      2.7.1            py27h75626f5_0
halotools                 0.6              py27h7f0db61_2    bccp
hdf5                      1.10.1               ha036c08_1
heapdict                  1.0.0            py27hb5e74ad_0
hypothesis                3.38.5           py27h3e2e078_0
idna                      2.6              py27hedea723_1
intel-openmp              2018.0.0             h8158457_8
ipaddress                 1.0.19                   py27_0
ipython                   5.4.1            py27h2b3d779_1
ipython_genutils          0.2.0            py27h8b9a179_0
jinja2                    2.10             py27h70b8dc5_0
kdcount                   0.3.27           py27h8d220f6_2    bccp
libcxx                    4.0.1                h579ed51_0
libcxxabi                 4.0.1                hebd6815_0
libedit                   3.1                  hb4e282d_0
libffi                    3.2.1                h475c297_4
libgfortran               3.0.1                h93005f0_2
libpng                    1.6.32               hd1e8b91_4
locket                    0.2.0            py27ha10513d_1
markupsafe                1.0              py27hd3c86fa_1
matplotlib                2.1.1            py27hb768455_0
mcfit                     0.0.7            py27h5d3c593_0    bccp
mkl                       2018.0.1             hfbd8650_4
mpc                       1.0.3                h7a72875_5
mpfr                      3.1.5                h711e7fd_2
mpi4py                    3.0.0           py27_openmpihcf1198f_5  [openmpi]  bccp
mpmath                    1.0.0            py27h6b0eff6_2
mpsort                    0.1.12          py27_openmpih0d69fe8_3  [openmpi]  bccp
msgpack-python            0.5.1            py27h04f5b5a_0
nbodykit                  0.3.0                    py27_3    bccp
ncurses                   6.0                  hd04f020_2
numexpr                   2.6.4            py27hf375000_0
numpy                     1.14.0           py27h8a80b8c_0
openmpi                   3.0.0                h9b8feb0_2    bccp
openssl                   1.0.2n               hdbc3d79_0
pandas                    0.22.0           py27h0a44026_0
partd                     0.3.8            py27h7560dbf_0
pathlib2                  2.3.0            py27he09da1e_0
pexpect                   4.3.1                    py27_0
pfft-python               0.1.15          py27_openmpih95c6a07_3  [openmpi]  bccp
pickleshare               0.7.4            py27h37e3d41_0
pip                       9.0.1            py27h1567d89_4
pluggy                    0.6.0            py27had36429_0
pmesh                     0.1.38           py27h6220244_2    bccp
prompt_toolkit            1.0.15           py27h4a7b9c2_0
psutil                    5.4.3            py27h1de35cc_0
ptyprocess                0.5.2            py27h70f6364_0
py                        1.5.2            py27he6783ac_0
pycparser                 2.18             py27h0d28d88_1
pygments                  2.2.0            py27h1a556bb_0
pympler                   0.5              py27hf3ee101_0
pyopenssl                 17.5.0           py27hfda213f_0
pyparsing                 2.2.0            py27h5bb6aaf_0
pysocks                   1.6.7            py27h1cff6a6_1
pytest                    3.3.2                    py27_0
python                    2.7.14              hde5916a_29
python-dateutil           2.6.1            py27hd56c96b_1
pytz                      2017.3           py27h803c07a_0
pyyaml                    3.12             py27ha7932d0_1
readline                  7.0                  hc1231fa_4
requests                  2.18.4           py27h9b2b37c_1
runtests                  0.0.25           py27h5a8e456_0    bccp
scandir                   1.6              py27h97aa1ee_0
scipy                     1.0.0            py27h793f721_0
setuptools                38.4.0                   py27_0
simplegeneric             0.8.1            py27h6db5e31_0
singledispatch            3.4.0.3          py27he22c18d_0
six                       1.11.0           py27h7252ba3_1
sortedcontainers          1.5.9                    py27_0
sqlite                    3.20.1               h7e4c145_2
ssl_match_hostname        3.5.0.1          py27h8780752_2
subprocess32              3.2.7            py27h24b2887_0
sympy                     1.1.1            py27hce55102_0
tblib                     1.3.2            py27ha684fc4_0
tk                        8.6.7                h35a86e2_3
toolz                     0.9.0                    py27_0
tornado                   4.5.3                    py27_0
traitlets                 4.3.2            py27hcf08151_0
urllib3                   1.22             py27hc3787e9_0
wcwidth                   0.1.7            py27h817c265_0
wheel                     0.30.0           py27h677a027_1
yaml                      0.1.7                hc338f04_2
zict                      0.1.3            py27h5fff8b1_0
zlib                      1.2.11               hf3cbc9b_2
zope                      1.0                      py27_0
zope.interface            4.4.3            py27h03e767a_0

**Comment by rainwoodman** [comment]
It appears that you are using some older binary files. Is there a way for
you to ensure you get, e.g. CorrFunc of version with string py27h24xxxxx_3
(and several other packages from bccp channel appear to be out of date as
well.

This can happen if your conda is  not up to date. What about you download
an anaconda 5.x and restart from scratch?

**Comment by cosmonomad** [comment]
Hi Yu, 
It finally worked after updating all bccp-related packages like "conda update -c bccp --all".
The errors that I reported disappeared when importing nbodykit lab. 
Thanks for your help to fix this problem.

**Comment by rainwoodman** [comment]
Thanks for testing!
