### ISSUE TITLE
Power spectrum multipoles of a randoms catalog

### ISSUE THREAD

**Issue by nickhand** [bccp/nbodykit#456]
To do window function multipoles (from a randoms catalog) using ConvolvedFFTPower, we essentially need to run the algorithm without a "data" catalog. We just need to check where we enforce that catalogs must be > 0

**Comment by michaelJwilson** [comment]
Hey Nick, just curious what the status is on this?  I'm 
assuming Byeonghee also has some idea.

Thanks!

Mike

**Comment by rainwoodman** [comment]
This feature has landed on the master branch. @ybh0822 tested this to some extent.
