### ISSUE TITLE
fire-bot does not seem activated

### ISSUE THREAD

**Issue by adematti** [bccp/nbodykit#474]
Hi,

I have tried to send an email containing bug reports to nbodykit-issues@fire.fundersclub.com (as suggested here: http://nbodykit.readthedocs.io/en/latest/help/support.html), but it failed.

Hey adematti,
I do not recognize the e-mail address nbodykit-issues@fire.fundersclub.com. Have you added fire (@fire-bot) to your repository? nbodykit-issues is not currently associated with any repository.
Thanks, Fire

Thanks,

adematti

**Comment by adematti** [comment]
Sorry I did not notice your previous issue #465. Would it be possible to edit (or not mention) the email address provided on the page: http://nbodykit.readthedocs.io/en/latest/help/support.html?
Sorry again, 
Thanks!

**Comment by rainwoodman** [comment]
Thanks for noticing this. Yes I had to turn off the firebot service due to excessive spammers. The documentation has been updated.
