### ISSUE TITLE
Renaming MeshSource.paint() to MeshSource.compute().

### ISSUE THREAD

**Issue by rainwoodman** [bccp/nbodykit#484]
It provides a more uniform appearance of the API. The documentation may need a search/replacement too.

The old .paint() function can be modified to issue a deprecation warning that points to the new compute() method.

**Comment by rainwoodman** [comment]
The `run()` methods in Algorithms can also be renamed to `compute()`.

**Comment by rainwoodman** [comment]
@nickhand do you recall why we didn't use `compute()` for all of these names?

**Comment by nickhand** [comment]
I don’t think we had a good reason....but I like the more uniform approach

**Comment by rainwoodman** [comment]
Perhaps it is because MeshSource.compute() need an extra argument to decide if real or complex is desired.
