### ISSUE TITLE
ConvolvedFFTPower never finishes with the unique k feature

### ISSUE THREAD

**Issue by ybh0822** [bccp/nbodykit#523]
If I set dk = 0, ConvolvedFFTPower stops after computing ell = 2 multipole:

- [ 000011.25 ]  142: 09-20 20:03  FKPCatalog      INFO     cartesian coordinate range: [-1847.34076385 -1700.90138172  -116.40005781] : [-122.37783978 1614.82433544 1720.44406775]
- [ 000015.10 ]   0: 09-20 20:03  ConvolvedFFTPower INFO     using compensation function CompensateTSC for source 'first'
- [ 000015.10 ]   0: 09-20 20:03  ConvolvedFFTPower INFO     using compensation function CompensateTSC for source 'second'
- /dev/shm/local/lib/python3.6/site-packages/nbodykit/algorithms/convpower/catalogmesh.py:170: RuntimeWarning: divide by zero encountered in long_scalars
- attrs['alpha'] = attrs['data.W'] / attrs['randoms.W']
- [ 000043.30 ]   0: 09-20 20:04  CatalogMesh     INFO     painted 25227245 out of 25227245 objects to mesh
- [ 000043.88 ]   0: 09-20 20:04  CatalogMesh     INFO     painted 25227245 out of 25227245 objects to mesh
- [ 000043.88 ]   0: 09-20 20:04  CatalogMesh     INFO     mean particles per cell is 0.0548924
- [ 000043.88 ]   0: 09-20 20:04  CatalogMesh     INFO     sum is 7.36753e+06 
- [ 000043.88 ]   0: 09-20 20:04  FKPCatalogMesh  INFO     data painted.
- [ 000043.88 ]   0: 09-20 20:04  FKPCatalogMesh  INFO     volume per cell is 104.258
- [ 000043.89 ]   0: 09-20 20:04  FKPCatalogMesh  INFO     field: <nbodykit.algorithms.convpower.catalogmesh.FKPCatalogMesh object at 0x2aaadf750cf8> painting done
- [ 000043.89 ]   0: 09-20 20:04  ConvolvedFFTPower INFO     tsc painting of 'first' done
- [ 000044.05 ]   0: 09-20 20:04  ConvolvedFFTPower INFO     ell = 0 done; 1 r2c completed
- [ 000044.16 ]   0: 09-20 20:04  ConvolvedFFTPower INFO     normalization of power spectrum is neglected, as no random is provided.
- [ 000045.04 ]   0: 09-20 20:04  ConvolvedFFTPower INFO     ell = 2 done; 5 r2c completed

I also asked the code to only compute the monopole and save the result, but similarly, the code cannot save the result after it's done computing all the multipoles:

[ 000017.63 ]   0: 09-20 20:33  ConvolvedFFTPower INFO     ell = 0 done; 1 r2c completed
[ 000017.74 ]   0: 09-20 20:33  ConvolvedFFTPower INFO     normalization of power spectrum is neglected, as no random is provided.
[ 000017.74 ]   0: 09-20 20:33  ConvolvedFFTPower INFO     higher order multipoles computed in elapsed time 00:00:00.00

Hmm, I believe you ran the test code with data and randoms but not with randoms only?

Thanks,
Byeonghee

**Comment by rainwoodman** [comment]
So we agreed it is just slow. We may be able to speed up this; but it is not urgent. Another way is to limit the number of bins by using a small dk. One can always get rid of the nan entries (modes == 0) by using the `take` method of the result.
