### ISSUE TITLE
memory estimation with ConvolvedFFTPower

### ISSUE THREAD

**Issue by Moctobers** [bccp/nbodykit#560]
Hi,

I am surprised to see the memory usage when running **ConvolvedFFTPower** on the Cori Haswell. When requiring 12 nodes, there is peak at about 95 GB/node. Eventually, the job is OOM-killed.

The data size is ~ 4e5 with a random about 20x times and the box size is L~3Gpc. In the setting, I am using mesh=1600, with window='tsc', interlaced=True, compensated=True.

thanks!

**Comment by rainwoodman** [comment]
This is a bit surprising indeed.

Which version of nbodykit are you using? Some earlier version has bugs in IO / slicing that uses more than necessary memory if you do subsampling of catalogs.


Also do you know when it peaks at 95GB / node what the code is outputting (run nbodykit.setup_logging() to get the verbose log)?

The mesh 1600**3 = 4 G points * 4 or 8 bytes per point = 16 GB or 32 GB per field, FKP needs several of them in memory at the same time. But this number is cross all ranks.

Sometimes job placement can do weird things like putting all ranks to a single node rather than spreading them round-robin on all nodes. Is there a way for you to rule this out?

**Comment by Moctobers** [comment]
Hi!

I am using the version 0.3.9 of nbodykit (with python3).

The memory error occurs at the step:

> ConvolvedFFTPower INFO     ell = 0 done; 1 r2c completed

Then the error message reads,

`slurmstepd: error: Detected 1 oom-kill event(s) in step 18348738.1 cgroup. Some of your processes may have been killed by the cgroup out-of-memory handler.`

**Comment by rainwoodman** [comment]
What if you launch hostname instead of python. Do you get different hostnames?

**Comment by Moctobers** [comment]
I tried to run:

`srun -n 8 -l hostname`

and, yes, it outputs 8 different hostnames. Is this your question?

**Comment by rainwoodman** [comment]
Yes. So this simple problem is ruled out. What data source do you read text from?

**Comment by rainwoodman** [comment]
What about posting the full logging output?

**Comment by rainwoodman** [comment]
Also, are you using the NERSC deployment (source /usr/common/contrib/bccp/conda-activate.sh 3.6), or the generic mpich-3.2 binaries from bccp channel?

I think if you launch the mpich-3.2 binary with srun, then the MPI communicator will not properly span cross a single node.

**Comment by Moctobers** [comment]
Hi, 

thanks for the reply!

The data source is from a mock simulation. 

When running the code, I use the one installed in my anaconda nbodykit environment (python 3) by following:
```
$ conda create --name nbodykit-env python=3 # or use python=2 for python 2.7*
$ source activate nbodykit-env
$ conda install -c bccp nbodykit
```

For demonstration and visibility, here is the log output of running the code on one node. It stops at the same point as I run on more nodes :

```
[ 000033.79 ]   0: 02-01 12:20  RedshiftHistogram INFO     using Scott's rule to determine optimal binning; h = 6.80e-03, N_bins = 206
[ 000035.13 ]   0: 02-01 12:20  RedshiftHistogram INFO     using cosmology {'output': 'vTk dTk mPk', 'extra metric transfer functions': 'y', 'h': 0.71, 'N_ur': 2.0328, 'gauge': 'synchronous', 'n_s': 0.9667, 'T_cmb': 2.7255, 'N_ncdm': 1, 'P_k_max_h/Mpc': 10.0, 'z_max_pk': 100.0, 'Omega_b': 0.04076693624753963, 'Omega_cdm': 0.22274526985651877, 'm_ncdm': [0.06]} to compute volume in units of (Mpc/h)^3
[ 000035.13 ]   0: 02-01 12:20  RedshiftHistogram INFO     sky fraction used in volume calculation: 0.0736
[ 000038.99 ]   0: 02-01 12:21  RedshiftHistogram INFO     using Scott's rule to determine optimal binning; h = 1.85e-02, N_bins = 76
[ 000039.04 ]   0: 02-01 12:21  RedshiftHistogram INFO     using cosmology {'output': 'vTk dTk mPk', 'extra metric transfer functions': 'y', 'h': 0.71, 'N_ur': 2.0328, 'gauge': 'synchronous', 'n_s': 0.9667, 'T_cmb': 2.7255, 'N_ncdm': 1, 'P_k_max_h/Mpc': 10.0, 'z_max_pk': 100.0, 'Omega_b': 0.04076693624753963, 'Omega_cdm': 0.22274526985651877, 'm_ncdm': [0.06]} to compute volume in units of (Mpc/h)^3
[ 000039.04 ]   0: 02-01 12:21  RedshiftHistogram INFO     sky fraction used in volume calculation: 0.0736
[ 000046.23 ]   0: 02-01 12:21  FKPCatalog      INFO     cartesian coordinate range: [-3945.60907007 -1499.8797836  -1499.88841271] : [-1299.89087857  1499.88835502  1499.88551553]
[ 000046.23 ]   0: 02-01 12:21  FKPCatalog      INFO     BoxSize = [2699. 3060. 3060.]
[ 000046.23 ]   0: 02-01 12:21  FKPCatalog      INFO     BoxCenter = [-2.62274997e+03  4.28571066e-03 -1.44858880e-03]
[ 000046.27 ]   0: 02-01 12:21  ConvolvedFFTPower INFO     using compensation function CompensateTSC for source 'first'
[ 000046.27 ]   0: 02-01 12:21  ConvolvedFFTPower INFO     using compensation function CompensateTSC for source 'second'
[ 000085.40 ]   0: 02-01 12:21  CatalogMesh     INFO     Chunk 0 ~ 4194304 / 423487 
[ 000087.40 ]   0: 02-01 12:21  CatalogMesh     INFO     painted 423487 out of 423487 objects to mesh
[ 000398.73 ]   0: 02-01 12:27  CatalogMesh     INFO     painted 423487 out of 423487 objects to mesh
[ 000398.73 ]   0: 02-01 12:27  CatalogMesh     INFO     mean particles per cell is 8.00873e-05
[ 000398.73 ]   0: 02-01 12:27  CatalogMesh     INFO     sum is 328038 
[ 000402.98 ]   0: 02-01 12:27  FKPCatalogMesh  INFO     data painted.
[ 000431.26 ]   0: 02-01 12:27  CatalogMesh     INFO     Chunk 0 ~ 4194304 / 8489905 
[ 000447.24 ]   0: 02-01 12:27  CatalogMesh     INFO     painted 4194304 out of 8489905 objects to mesh
[ 000447.24 ]   0: 02-01 12:27  CatalogMesh     INFO     Chunk 4194304 ~ 8388608 / 8489905 
[ 000457.65 ]   0: 02-01 12:27  CatalogMesh     INFO     painted 8388608 out of 8489905 objects to mesh
[ 000457.65 ]   0: 02-01 12:27  CatalogMesh     INFO     Chunk 8388608 ~ 12582912 / 8489905 
[ 000457.94 ]   0: 02-01 12:27  CatalogMesh     INFO     painted 8489905 out of 8489905 objects to mesh
[ 000778.61 ]   0: 02-01 12:33  CatalogMesh     INFO     painted 8489905 out of 8489905 objects to mesh
[ 000778.61 ]   0: 02-01 12:33  CatalogMesh     INFO     mean particles per cell is 0.00160542
[ 000778.61 ]   0: 02-01 12:33  CatalogMesh     INFO     sum is 6.5758e+06 
[ 000786.70 ]   0: 02-01 12:33  FKPCatalogMesh  INFO     randoms painted.
[ 000796.98 ]   0: 02-01 12:33  FKPCatalogMesh  INFO     volume per cell is 6.17001
[ 000798.04 ]   0: 02-01 12:33  FKPCatalogMesh  INFO     field: <nbodykit.algorithms.convpower.catalogmesh.FKPCatalogMesh object at 0x2aaac1610748> painting done
[ 000798.04 ]   0: 02-01 12:33  ConvolvedFFTPower INFO     tsc painting of 'first' done
[ 000930.62 ]   0: 02-01 12:35  ConvolvedFFTPower INFO     ell = 0 done; 1 r2c completed

slurmstepd: error: Detected 1 oom-kill event(s) in step 18434298.4 cgroup. Some of your processes may have been killed by the cgroup out-of-memory handler.
srun: error: nid00015: task 0: Out Of Memory
srun: Terminating job step 18434298.4

```

**Comment by rainwoodman** [comment]
I see.  This error is expected then.

You are using the mpich-3.2 binaries on NERSC, which cannot make use of
more than 1 node.

Replace source actitvate nbodykit-env with:

source /usr/common/contrib/bccp/conda-activate.sh 3.6

which will give you a python environment at /dev/shm (bcast-anaconda-3.6)
that also has nbodykit installed.

**Comment by Moctobers** [comment]
Hi,

sorry for the delayed update. The memory error is finally solved! Thanks!

However, now I have a different problem. When setting  

`srun -n 4 `

I get a different answer for the power spectrum (which doesn't look correct) than using `srun -1`.

I am not sure if I should open a new thread or this issue is already recognized previously?

**Comment by rainwoodman** [comment]
Yes. We shall open a new thread. I'll close this one as the memory issue is solved. It is a mix up between MPI binaries. We do need to find a way to minimize the chances for this to occur.

Could you post the relative difference of the two power spectrum as well, e.g.

(P1 - P2) / (P1 + P2)
