### ISSUE TITLE
mix up between MPI binaries

### ISSUE THREAD

**Issue by Moctobers** [bccp/nbodykit#568]
Hi,

when using **ConvolvedFFTPower** I got a different value for running the same code w/w.o parallelisation:

`srun -n 4` or `srun -n 1`

The k range is: 

> [0.00364618, 0.00793205, 0.01281354, 0.01773466, 0.02271201,
>        0.027675  , 0.03263365, 0.03762105, 0.04261554, 0.04761876,
>        0.05260162, 0.05757362, 0.06256442, 0.06756922, 0.07255943,
>        0.0775455 , 0.08254604, 0.08755272, 0.09255216, 0.0975438 ,
>        0.10253779, 0.10754069, 0.11253619, 0.11753287, 0.12253625,
>        0.1275271 , 0.1325203 , 0.13752506, 0.14252776, 0.14753151,
>        0.1525287 , 0.15752283, 0.16252421, 0.16752603, 0.17252399,
>        0.17752556, 0.18252847, 0.18752467, 0.19251992]

The difference the two power spectrum (P(srun4)-P(srun1))/(P(srun4)+P(srun1)) is:

P0-Pshotnoise: 

> [ 0.98814195  0.5600344  -0.10838911 -0.2176312  -0.24565904 -0.24857719
>  -0.26419994 -0.25621548 -0.25413454 -0.2614868  -0.25489697 -0.25982034
>  -0.25660288 -0.2608773  -0.25911412 -0.25651196 -0.25976828 -0.25758716
>  -0.2524169  -0.25718898 -0.253251   -0.25012192 -0.2548281  -0.2541806
>  -0.25298002 -0.2572376  -0.2500575  -0.25450626 -0.26528376 -0.2551723
>  -0.25197324 -0.2511488  -0.2552239  -0.25197554 -0.24874635 -0.25438148
>  -0.24953723 -0.25414166 -0.260192  ]
> 

P2: 

> [ 0.956556    0.5677593  -0.15393549 -0.32663462 -0.25771353 -0.20143831
>  -0.22935504 -0.21151686 -0.2834506  -0.13824758 -0.46460414 -0.45418167
>  -0.28200838 -0.24116808 -0.28339878 -0.29778576 -0.2593428  -0.26754507
>  -0.2616602  -0.26493096 -0.26347482 -0.23377168 -0.2793503  -0.23306632
>  -0.26328403 -0.2532544  -0.24126036 -0.24739495 -0.25983298 -0.2606769
>  -0.2495388  -0.26241985 -0.28549883 -0.27392295 -0.25152946 -0.270585
>  -0.252011   -0.247738   -0.26426378]

(I am not sure whether the title for this issue is clear enough, let me know if I could improve it)

**Comment by Moctobers** [comment]
Hi,

> Did you run this with the python environment provided by '/usr/contrib/common/bccp/conda-activate.sh'?

yes, I am running with python environment provided by '/usr/contrib/common/bccp/conda-activate.sh'?

> Always pair srun with that environment -- and make sure you don't accidentally activate another python environment after it.

I didn't activate another python environment after it, at least not that I am aware of .. Is there way of confirming this point ?

**Comment by rainwoodman** [comment]
which python shall give you a file from /dev/shm.

**Comment by rainwoodman** [comment]
I have seen a similar issue. I ran ConvolvedFFTPower on different datasets, and I get different k values. I think it is due to the estimation of box size in my case -- different box sizes were inferred from different datasets.

Could you post the full log out put of the two runs? Let's see if the inferred box sizes are somehow dependent on the rank.

**Comment by Moctobers** [comment]
Hi,

first comes the log for running the code with `srun -n 1`:

> OMP: Warning #181: OMP_PROC_BIND: ignored because KMP_AFFINITY has been defined
> OMP: Warning #181: OMP_PLACES: ignored because KMP_AFFINITY has been defined
> [ 000003.20 ]   0: 02-13 13:31  RedshiftHistogram INFO     using Scott's rule to determine optimal binning; h = 6.80e-03, N_bins = 208
> [ 000004.02 ]   0: 02-13 13:31  RedshiftHistogram INFO     using cosmology {'output': 'vTk dTk mPk', 'extra metric transfer functions': 'y', 'n_s': 0.9667, 'gauge': 'synchronous', 'N_ur': 2.0328, 'h': 0.71, 'T_cmb': 2.7255, 'N_ncdm': 1, 'P_k_max_h/Mpc': 10.0, 'z_max_pk': 100.0, 'Omega_b': 0.04076693624753963, 'Omega_cdm': 0.22274526985651877, 'm_ncdm': [0.06]} to compute volume in units of (Mpc/h)^3
> [ 000004.02 ]   0: 02-13 13:31  RedshiftHistogram INFO     sky fraction used in volume calculation: 0.0738
> [ 000007.23 ]   0: 02-13 13:31  RedshiftHistogram INFO     using Scott's rule to determine optimal binning; h = 1.85e-02, N_bins = 77
> [ 000007.26 ]   0: 02-13 13:31  RedshiftHistogram INFO     using cosmology {'output': 'vTk dTk mPk', 'extra metric transfer functions': 'y', 'n_s': 0.9667, 'gauge': 'synchronous', 'N_ur': 2.0328, 'h': 0.71, 'T_cmb': 2.7255, 'N_ncdm': 1, 'P_k_max_h/Mpc': 10.0, 'z_max_pk': 100.0, 'Omega_b': 0.04076693624753963, 'Omega_cdm': 0.22274526985651877, 'm_ncdm': [0.06]} to compute volume in units of (Mpc/h)^3
> [ 000007.26 ]   0: 02-13 13:31  RedshiftHistogram INFO     sky fraction used in volume calculation: 0.0738
> [ 000014.52 ]   0: 02-13 13:31  FKPCatalog      INFO     cartesian coordinate range: [-3945.8010079  -1506.1482802  -1508.15682473] : [-1295.13003806  1506.6887611   1504.52469419]
> [ 000014.52 ]   0: 02-13 13:31  FKPCatalog      INFO     BoxSize = [2704. 3074. 3073.]
> [ 000014.52 ]   0: 02-13 13:31  FKPCatalog      INFO     BoxCenter = [-2.62046552e+03  2.70240453e-01 -1.81606527e+00]
> [ 000014.53 ]   0: 02-13 13:31  ConvolvedFFTPower INFO     using compensation function CompensateTSC for source 'first'
> [ 000014.53 ]   0: 02-13 13:31  ConvolvedFFTPower INFO     using compensation function CompensateTSC for source 'second'
> [ 000020.06 ]   0: 02-13 13:31  CatalogMesh     INFO     Chunk 0 ~ 4194304 / 423488
> [ 000020.53 ]   0: 02-13 13:31  CatalogMesh     INFO     painted 423488 out of 423488 objects to mesh
> [ 000021.45 ]   0: 02-13 13:31  CatalogMesh     INFO     painted 423488 out of 423488 objects to mesh
> [ 000021.45 ]   0: 02-13 13:31  CatalogMesh     INFO     mean particles per cell is 0.0195721
> [ 000021.45 ]   0: 02-13 13:31  CatalogMesh     INFO     sum is 328366
> [ 000021.46 ]   0: 02-13 13:31  FKPCatalogMesh  INFO     data painted.
> [ 000021.58 ]   0: 02-13 13:31  CatalogMesh     INFO     Chunk 0 ~ 4194304 / 8489905
> [ 000027.60 ]   0: 02-13 13:31  CatalogMesh     INFO     painted 4194304 out of 8489905 objects to mesh
> [ 000027.60 ]   0: 02-13 13:31  CatalogMesh     INFO     Chunk 4194304 ~ 8388608 / 8489905
> [ 000033.62 ]   0: 02-13 13:31  CatalogMesh     INFO     painted 8388608 out of 8489905 objects to mesh
> [ 000033.62 ]   0: 02-13 13:31  CatalogMesh     INFO     Chunk 8388608 ~ 12582912 / 8489905
> [ 000033.82 ]   0: 02-13 13:31  CatalogMesh     INFO     painted 8489905 out of 8489905 objects to mesh
> [ 000034.74 ]   0: 02-13 13:31  CatalogMesh     INFO     painted 8489905 out of 8489905 objects to mesh
> [ 000034.74 ]   0: 02-13 13:31  CatalogMesh     INFO     mean particles per cell is 0.392374
> [ 000034.74 ]   0: 02-13 13:31  CatalogMesh     INFO     sum is 6.58295e+06
> [ 000034.77 ]   0: 02-13 13:31  FKPCatalogMesh  INFO     randoms painted.
> [ 000034.82 ]   0: 02-13 13:31  FKPCatalogMesh  INFO     volume per cell is 1522.49
> [ 000034.82 ]   0: 02-13 13:31  FKPCatalogMesh  INFO     field: (FKPCatalog(species=['data', 'randoms']) as CatalogMesh) painting done
> [ 000034.82 ]   0: 02-13 13:31  ConvolvedFFTPower INFO     tsc painting of 'first' done
> [ 000035.23 ]   0: 02-13 13:31  ConvolvedFFTPower INFO     ell = 0 done; 1 r2c completed
> [ 000044.09 ]   0: 02-13 13:32  ConvolvedFFTPower INFO     normalized power spectrum with `randoms.norm = 7.165825`
> [ 000046.15 ]   0: 02-13 13:32  ConvolvedFFTPower INFO     ell = 2 done; 5 r2c completed
> [ 000051.44 ]   0: 02-13 13:32  ConvolvedFFTPower INFO     ell = 4 done; 9 r2c completed
> [ 000052.44 ]   0: 02-13 13:32  ConvolvedFFTPower INFO     higher order multipoles computed in elapsed time 00:00:08.35
> [ 000061.43 ]   0: 02-13 13:32  ConvolvedFFTPower INFO     saving ConvolvedFFTPower result to test_srun1.json
> sky fraction = 0.07383293789761837
> max{x, y, z} 3009.9521235372667
> kny resolution= 0.26719618329803957
> nbar =  2.7079871919013623e-05 ,neff =  2.4358945992173094e-05 @z= 1.4514982116629358
> Veff =  10751976151.760786 ,recon =  True
> mesh done
>

**Comment by Moctobers** [comment]
here is with `srun -n 2`:

> OMP: Warning #181: OMP_PROC_BIND: ignored because KMP_AFFINITY has been defined
> OMP: Warning #181: OMP_PLACES: ignored because KMP_AFFINITY has been defined
> OMP: Warning #181: OMP_PROC_BIND: ignored because KMP_AFFINITY has been defined
> OMP: Warning #181: OMP_PLACES: ignored because KMP_AFFINITY has been defined
> [ 000002.25 ]   0: 02-11 01:16  RedshiftHistogram INFO     using Scott's rule to determine optimal binning; h = 6.80e-03, N_bins = 208
> [ 000002.67 ]   0: 02-11 01:17  RedshiftHistogram INFO     using cosmology {'output': 'vTk dTk mPk', 'extra metric transfer functions': 'y', 'n_s': 0.9667, 'gauge': 'synchronous', 'N_ur': 2.0328, 'h': 0.71, 'T_cmb': 2.7255, 'N_ncdm': 1, 'P_k_max_h/Mpc': 10.0, 'z_max_pk': 100.0, 'Omega_b': 0.04076693624753963, 'Omega_cdm': 0.22274526985651877, 'm_ncdm': [0.06]} to compute volume in units of (Mpc/h)^3
> [ 000002.67 ]   0: 02-11 01:17  RedshiftHistogram INFO     sky fraction used in volume calculation: 0.0711
> [ 000004.55 ]   0: 02-11 01:17  RedshiftHistogram INFO     using Scott's rule to determine optimal binning; h = 1.85e-02, N_bins = 77
> [ 000004.57 ]   0: 02-11 01:17  RedshiftHistogram INFO     using cosmology {'output': 'vTk dTk mPk', 'extra metric transfer functions': 'y', 'n_s': 0.9667, 'gauge': 'synchronous', 'N_ur': 2.0328, 'h': 0.71, 'T_cmb': 2.7255, 'N_ncdm': 1, 'P_k_max_h/Mpc': 10.0, 'z_max_pk': 100.0, 'Omega_b': 0.04076693624753963, 'Omega_cdm': 0.22274526985651877, 'm_ncdm': [0.06]} to compute volume in units of (Mpc/h)^3
> [ 000004.57 ]   0: 02-11 01:17  RedshiftHistogram INFO     sky fraction used in volume calculation: 0.0711
> [ 000008.16 ]   0: 02-11 01:17  FKPCatalog      INFO     cartesian coordinate range: [-3945.8010079  -1506.1482802  -1508.15682473] : [-1295.13003806  1506.6887611   1504.52469419]
> [ 000008.16 ]   0: 02-11 01:17  FKPCatalog      INFO     BoxSize = [2704. 3074. 3073.]
> [ 000008.16 ]   0: 02-11 01:17  FKPCatalog      INFO     BoxCenter = [-2.62046552e+03  2.70240453e-01 -1.81606527e+00]
> [ 000008.17 ]   0: 02-11 01:17  ConvolvedFFTPower INFO     using compensation function CompensateTSC for source 'first'
> [ 000008.17 ]   0: 02-11 01:17  ConvolvedFFTPower INFO     using compensation function CompensateTSC for source 'second'
> [ 000011.73 ]   0: 02-11 01:17  CatalogMesh     INFO     Chunk 0 ~ 4194304 / 211744
> [ 000012.00 ]   0: 02-11 01:17  CatalogMesh     INFO     painted 423488 out of 423488 objects to mesh
> [ 000012.54 ]   0: 02-11 01:17  CatalogMesh     INFO     painted 423488 out of 423488 objects to mesh
> [ 000012.54 ]   0: 02-11 01:17  CatalogMesh     INFO     mean particles per cell is 0.0188
> [ 000018.81 ]   0: 02-11 01:17  CatalogMesh     INFO     sum is 6.32326e+06
> [ 000018.82 ]   0: 02-11 01:17  FKPCatalogMesh  INFO     randoms painted.
> [ 000018.84 ]   0: 02-11 01:17  FKPCatalogMesh  INFO     volume per cell is 1522.49
> [ 000018.85 ]   0: 02-11 01:17  FKPCatalogMesh  INFO     field: (FKPCatalog(species=['data', 'randoms']) as CatalogMesh) painting done
> [ 000018.85 ]   0: 02-11 01:17  ConvolvedFFTPower INFO     tsc painting of 'first' done
> [ 000019.07 ]   0: 02-11 01:17  ConvolvedFFTPower INFO     ell = 0 done; 1 r2c completed
> [ 000023.45 ]   0: 02-11 01:17  ConvolvedFFTPower INFO     normalized power spectrum with `randoms.norm = 7.775841`
> [ 000024.61 ]   0: 02-11 01:17  ConvolvedFFTPower INFO     ell = 2 done; 5 r2c completed
> [ 000027.43 ]   0: 02-11 01:17  ConvolvedFFTPower INFO     ell = 4 done; 9 r2c completed
> [ 000027.90 ]   0: 02-11 01:17  ConvolvedFFTPower INFO     higher order multipoles computed in elapsed time 00:00:04.45
> [ 000032.27 ]   0: 02-11 01:17  ConvolvedFFTPower INFO     saving ConvolvedFFTPower result to testsrun2.json
> sky fraction = 0.05466044076878073
> max{x, y, z} 3007.736724936756
> kny resolution= 0.267392991098946
> nbar =  3.657830916749468e-05 ,neff =  3.290300117226211e-05 @z= 1.4514982116629358
> Veff =  8267226420.811521 ,recon =  True
> mesh done
> save pk at /global/cscratch1/sd/octobers/Projects/Simulation/OuterRim/pk/postrecon/
> sky fraction = 0.07111463132122466
> max{x, y, z} 3009.7847316489137
> kny resolution= 0.26721104365440085
> nbar =  2.811498090513564e-05 ,neff =  2.5290049505674415e-05 @z= 1.4514982116629358
> Veff =  10401702155.46887 ,recon =  True
> mesh done

**Comment by nickhand** [comment]
It looks like the sky fraction logged by RedshiftHistogram is different for n = 1 and n = 2 runs. Maybe it's calculating different n(z) values....are the input data sets randomly generated at all? This could also explain why `randoms.norm` is different for the two runs.

**Comment by rainwoodman** [comment]
@Moctobers fsky is an input to the RedshiftHistogram function call.

Could you take a look why different values are fed to it (0.0738 vs 0.0711)? If you are operating on the same data set it should have been the same. Perhaps you forgot to compute the total area on all MPI ranks with a call to `comm.allreduce()`.

**Comment by Moctobers** [comment]
ok, the problem was indeed fsky. Before I calculated it by taking the difference between min/max of catalog['{ra,dec}']. Now I input it as a constant and the output is correct. Thanks!

Is there an exsiting routine of calculating fsky?

**Comment by rainwoodman** [comment]
Unfortunately there isn't any.

You can estimate this from the random catalog if you know the `designed density` of the random catalog -- the number density before the sky mask is applied.
