### ISSUE TITLE
Help with the full 3D k vector on a grid

### ISSUE THREAD

**Issue by obuljen** [bccp/nbodykit#572]
Hi, 

I have been using nbodykit recently and it's really nice! 
Right now I need to compute the tidal field on a grid and for that I need the full 3D wavenumber vector (kx, ky & kz). I have been trying to understand how do I get those once I have computed the delta's on a grid, but couldn't quite figure it out, even though I went through the tutorials several times...
Could you please help me out how to get those?

Thanks and bests,
Andrej

**Comment by rainwoodman** [comment]
`to_mesh(...).compute('complex') ` [or `.paint`] will give you a pmesh.pm.ComplexField object
( http://rainwoodman.github.io/pmesh/pmesh.pm.html#pmesh.pm.BaseComplexField), which is the complex field distributed on different ranks.

The object has an `apply` method that allows you to apply a point by point transformation based on k vectors.
You can also directly create a ComplexField, then ues apply to fill the values.

For example,
- A complex field filled with `kx`:
```
field = pm.create('complex', value=1).apply(lambda k, v: k[0] * v)
```
- A complex field filled with `k^2`:
```
field = pm.create('complex', value=1).apply(lambda k, v: k.normp(2) * v)
```

**Comment by obuljen** [comment]
Thank you very much!

Bests,
Andrej
