### ISSUE TITLE
Bug in CatalogMesh.to_real_field(), when particle chunk size is throttled

### ISSUE THREAD

**Issue by sjforeman** [bccp/nbodykit#575]
I believe there is a bug in CatalogMesh.to_real_field. Consider lines 303-332 of nbodykit.source.mesh.catalog. The second line of the "try" attempts to increase chunksize if it has previously been throttled. However, the placement of this increase can lead to particles that are skipped in the loop, and not assigned to the grid. Specifically, the following sequence can occur:
- chunksize starts at value c1, and the loop attempts to grid particles in slice(i,i+c1)
- a StopIteration is encountered, so chunksize is reduced to c2 and the iteration is restarted
- the loop grids particles in slice(i,i+c2)
- chunksize is increased to value c3, with c2<c3<c1
- i is incremented to i+c3
- the next iteration attempts to grid particles in slice (i+c3,i+2*c3)
- *however*, the particles in slice (i+c2+1,i+c3) have been completely skipped!
(I have recently encountered this situation in some tests involving painting Gadget particle snapshots to a mesh).

This can be fixed if the second line of the "try" is relocated to the end of the loop (in line numbers, moving line 312 to line 333, keeping the command within the while loop).

**Comment by rainwoodman** [comment]
Yes. This is indeed a bug. chunksize adjustment shall always occur after the sliding window is moved. Do you want to file a PR with the fix?
