### ISSUE TITLE
nbodykit at nersc cori removed?

### ISSUE THREAD

**Issue by Moctobers** [bccp/nbodykit#595]
Hi all,

when try to activate the nbodykit at cori nersc I realised that the directory 

> /usr/common/contrib

is now empty.

**Comment by rainwoodman** [comment]
expected outage related to OS upgrade on Cori. Will fix it by 31st July.

**Comment by rainwoodman** [comment]
Please use the new location:

source /global/common/software/m3035/conda-activate.sh 3.7

There is only 3.7 due to a disk quota issue. I will add python 2.7 and 3.6 after it is resolved. 
Meanwhile I hope this can be a motivation for people to try out 3.7.

**Comment by Moctobers** [comment]
I got permission denid as I try to souce the new location:

```
namei -l /global/common/software/m3035
f: /global/common/software/m3035
drwxr-xr-x root   root  /
drwxr-xr-x root   root  global
drwxr-xr-x root   root  common
drwxr-xr-x root   root  software
drwxrws--- yfeng1 m3035 m3035
```

**Comment by rainwoodman** [comment]
Oops. I think this is fixed now. Try again?

**Comment by Moctobers** [comment]
perfect, it works now, thanks!
