### ISSUE TITLE
module "six" cannot be imported from "astropy.extern"

### ISSUE THREAD

**Issue by zdplayground** [bccp/nbodykit#609]
**Describe the bug**
Module "six" cannot be imported from "astropy.extern", e.g., "from astropy.extern import six" outputs error. 

**Steps To Reproduce**
I followed the example shown in https://nbodykit.readthedocs.io/en/latest/cookbook/hod-mocks.html#Generating-Halos-via-the-FOF-Algorithm. When I ran "halotools_halos = halos.to_halotools()", error occurs.

**Version**
Version of "astropy" is 3.2.3 and version of nbodykit is 0.3.13.

**Comment by jmsull** [comment]
@rainwoodman This has been solved with the latest halotools version and should be closed, see halotools [https://github.com/astropy/halotools/pull/945](945)

**Comment by jmsull** [comment]
@rainwoodman @zdplayground This has been solved, as halotools v0.7 and astropy 4.0 includes external six  (https://github.com/astropy/halotools/pull/945#issue-307174519)

**Comment by rainwoodman** [comment]
I second this. @zdplayground feel free to reopen if you are still affected.
