### ISSUE TITLE
Bug in Gaussian filter in filters.py

### ISSUE THREAD

**Issue by svonhausegger** [bccp/nbodykit#612]
The Gaussian filter in nbodykit/filters.py only smooths a mesh via `mesh.apply(Gaussian(r))` if

`return numpy.exp(- 0.5 * k2 * r**2)` 

instead reads 

`return numpy.exp(- 0.5 * k2 * r**2) * v`

in line 58.

**Comment by rainwoodman** [comment]
Yes. It is a bug. Will you file a PR?

**Comment by svonhausegger** [comment]
Yep, just did.
