### ISSUE TITLE
Projected FFT_Power function

### ISSUE THREAD

**Issue by andrearubiola** [bccp/nbodykit#616]
Good morning, 

I'd need to reproduce this paper's results: https://arxiv.org/abs/1609.00019. 
In particular, I'm interested in generating the 1d power spectrum of a HI intensity map as of equation 9 of the aforementioned paper. Is the ProjectedFFTPower function, with axes set to (0,1) useful for my goal? I'm writing here because the mathematical description of the function has not been implemented on nbodykit's page yet.
Thanks,
Regards

Andrea Rubiola

**Comment by rainwoodman** [comment]
Yes, I think so. More details in my other email.

Yu

**Comment by andrearubiola** [comment]
Thanks!
