### ISSUE TITLE
Issue with project_to_basis in FFTPower

### ISSUE THREAD

**Issue by jmsull** [bccp/nbodykit#617]
I get the following when running FFTPower: AttributeError: 'TransposedComplexField' object has no attribute 'compressed'

Here is a minimal example using the lognormal catalog essentially copied from the cookbook:

<img width="1078" alt="nbk_bug_fftpower" src="https://user-images.githubusercontent.com/50674574/82959437-8d0dd600-9f6c-11ea-9a1e-a4009c7ee070.png">

I am using the dev version ('0.3.14dev0') of nbodykit (on nersc) - I can downgrade if that will fix the issue.

Tagging @rainwoodman and @akrolewski since he edited the fftpower.py file recently

**Comment by rainwoodman** [comment]
Probably update pmesh to the latest version, 0.1.55? The 'compresseed' attribute is added recently to support @akrolewski  's changes.  [1]

[1] https://github.com/rainwoodman/pmesh/commit/39f1174cbafaf5d48d0ddbdf3e3b41ae07797a2f

**Comment by jmsull** [comment]
@rainwoodman Seems to fix - thanks! Closing
