### ISSUE TITLE
Problem with nbodykit.plugins.datasource

### ISSUE THREAD

**Issue by andrea0292** [bccp/nbodykit#619]
Dear Yu,

I have been trying to install Nbodykit; as suggested I used Anaconda to do it, following the instructions in your page (creating a new env). The installation goes smoothly, however when I then try to use it in my Jupyter notebook I get errors. I tried to update conda, so all the packages should be ok. Do you have any clue of the problem? Maybe Python version?  The error I get reads as follows

 "ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-95586280b629> in <module>
----> 1 from nbodykit.lab import *
      2 from nbodykit import style, setup_logging
      3 
      4 import matplotlib.pyplot as plt

~/anaconda3/lib/python3.7/site-packages/nbodykit/__init__.py in <module>
----> 1 from nbodykit.pluginmanager import load_builtins
      2 import os
      3 
      4 load_builtins()
      5 

~/anaconda3/lib/python3.7/site-packages/nbodykit/pluginmanager.py in <module>
     10 import nbodykit.plugins
     11 import nbodykit.plugins.algorithms
---> 12 import nbodykit.plugins.datasource
     13 import nbodykit.plugins.painter
     14 import nbodykit.plugins.transfer

ModuleNotFoundError: No module named 'nbodykit.plugins.datasource' "

Thanks a lot in advance,

Andrea

**Comment by rainwoodman** [comment]
My gut feeling is that you got an very old version of nbodykit (0.1.x).

What do you get with conda list?

Did you see any warnings from conda (e.g. conflicting packages) when installing nbodykit?

**Comment by andrea0292** [comment]
Dear Yu,

thanks a lot for the fast reply! This is the conda list I get, and no I didn’t get any Warning during the installation apparently..I also tried with the Source installation but doesn’t seem to help..

A

21cmfast                  3.0.0.dev0               pypi_0    pypi
_anaconda_depends         2019.03                  py37_0
_ipyw_jlab_nb_ext_conf    0.1.0                    py37_0
_r-mutex                  1.0.1               anacondar_1    conda-forge
alabaster                 0.7.12                   py37_0
anaconda                  custom                   py37_1
anaconda-client           1.7.2                    py37_0
anaconda-navigator        1.9.2                    py37_0
anaconda-project          0.8.4                      py_0
appnope                   0.1.0                    py37_0
appscript                 1.1.0            py37h1de35cc_0
asgiref                   3.2.7                    pypi_0    pypi
asn1crypto                1.3.0                    py37_0
astroid                   2.3.3                    py37_0
astropy                   3.2.3            py37h1de35cc_0
atomicwrites              1.3.0                    py37_1
attrs                     19.3.0                     py_0
autobahn                  18.12.1                  pypi_0    pypi
autograd                  1.3                      pypi_0    pypi
autograde                 0.1.1                    pypi_0    pypi
babel                     2.8.0                      py_0
backcall                  0.1.0                    py37_0
backports                 1.0                        py_2
backports.os              0.1.1                    py37_0
backports.shutil_get_terminal_size 1.0.0                    py37_2
beautifulsoup4            4.8.2                    py37_0
bigfile                   0.1.49           py37h776bbcc_7    bccp
bitarray                  1.2.1            py37h1de35cc_0
bkcharts                  0.2                      py37_0
blas                      1.0                         mkl
bleach                    3.1.0                    py37_0
blosc                     1.16.3               hd9629dc_0
bokeh                     1.4.0                    py37_0
boto                      2.49.0                   py37_0
bottleneck                1.3.1            py37h1d22016_0
build                     1.0.2                    pypi_0    pypi
bwidget                   1.9.14                        0    conda-forge
bzip2                     1.0.8                h1de35cc_0
ca-certificates           2020.4.5.1           hecc5488_0    conda-forge
cached-property           1.5.1                    pypi_0    pypi
cachey                    0.2.1                    py37_0    bccp
cairo                     1.16.0            h0ab9d94_1001    conda-forge
camb                      1.0.8                    pypi_0    pypi
cartopy                   0.17.0          py37h95120c7_1007    conda-forge
casjobs                   0.0.1                    pypi_0    pypi
cctools                   895                  h7512d6f_0
certifi                   2020.4.5.1               py37_0    anaconda
cffi                      1.13.2           py37hb5b8e2f_0
cfitsio                   3.470                h389770f_2    conda-forge
chardet                   3.0.4                 py37_1003
clang                     4.0.1                h662ec87_0    anaconda
clang_osx-64              4.0.1               h1ce6c1d_17    conda-forge
clangxx                   4.0.1                hc9b4283_0    conda-forge
clangxx_osx-64            4.0.1               h22b1bf0_17    conda-forge
classy                    2.7.2                    pypi_0    pypi
classylss                 0.2.9            py37hd5f3a30_7    bccp
click                     7.0                      py37_0
cloog                     0.18.0                        0    anaconda
cloudpickle               1.3.0                      py_0
clyent                    1.2.2                    py37_1
cmasher                   1.2.2                    pypi_0    pypi
colorama                  0.4.3                      py_0
colorspacious             1.1.2                    pypi_0    pypi
compiler-rt               4.0.1                h5487866_0
conda                     4.8.3            py37hc8dfbb8_1    conda-forge
conda-build               3.15.1                   py37_0
conda-env                 2.6.0                         1
conda-package-handling    1.6.0            py37h1de35cc_0
contextlib2               0.6.0.post1                py_0
corner                    2.0.1                    pypi_0    pypi
corrfunc                  2.3.0           py37h776bbcc_10    bccp
coverage                  5.1              py37h9bfed18_0    conda-forge
cryptography              2.8              py37ha12b0ac_0
curl                      7.68.0               ha441bb4_0
cycler                    0.10.0                   py37_0
cython                    0.29.14                  pypi_0    pypi
cytoolz                   0.10.1           py37h1de35cc_0
dask                      2.10.1                     py_0
dask-core                 2.10.1                     py_0
dbus                      1.13.12              h90a0687_0
decorator                 4.4.1                      py_0
defusedxml                0.6.0                      py_0
dill                      0.3.1.1                  pypi_0    pypi
distributed               2.10.0                     py_0
django                    3.0.5                    pypi_0    pypi
django-extensions         2.2.9                    pypi_0    pypi
django-tastypie           0.14.3                   pypi_0    pypi
docutils                  0.16                     py37_0
emcee                     2.2.1                    pypi_0    pypi
entrypoints               0.3                      py37_0
et_xmlfile                1.0.1                    py37_0
expat                     2.2.6                h0a44026_0
fastcache                 1.1.0            py37h1de35cc_0
fftw                      3.3.8           nompi_h5c49c53_1106    conda-forge
filelock                  3.0.12                     py_0
fitsio                    1.1.1            py37h234edc7_2    conda-forge
flask                     1.1.1                      py_0
fontconfig                2.13.1            h1027ab8_1000    conda-forge
freetype                  2.9.1                hb4e5f40_0
fribidi                   1.0.9                h0b31af3_0    conda-forge
fsspec                    0.6.2                      py_0
future                    0.18.2           py37hc8dfbb8_1    conda-forge
gcc                       4.8.5                         8    anaconda
geos                      3.7.2                h6de7cb9_2    conda-forge
get_terminal_size         1.0.0                h7520d66_0
gettext                   0.19.8.1             h15daf44_3
gevent                    1.4.0            py37h1de35cc_0
gfortran_osx-64           4.8.5                h22b1bf0_8    anaconda
glib                      2.63.1               hd977a24_0
glob2                     0.7                        py_0
gmp                       6.1.2                hb37e062_1
gmpy2                     2.0.8            py37h6ef4df4_2
graph                     1.11                 h0bee7d0_0    conda-forge
graphite2                 1.3.13            h2098e52_1000    conda-forge
greenlet                  0.4.15           py37h1de35cc_0
gsl                       2.4                  h1de35cc_4
gwdet                     0.1.1                    pypi_0    pypi
h5py                      2.8.0            py37h878fce3_3
halotools                 0.7              py37h6c726b0_5    bccp
harfbuzz                  2.4.0                h92b87b8_1    conda-forge
hdf5                      1.10.2               hfa1e0ec_1
healpy                    1.12.10          py37h2c3d0c3_0    conda-forge
heapdict                  1.0.1                      py_0
html5lib                  1.0.1                    py37_0
hypothesis                5.4.1                      py_0
icu                       58.2                 h4b95b61_1
idna                      2.8                      py37_0
imageio                   2.6.1                    py37_0
imagesize                 1.2.0                      py_0
iminuit                   1.3.7            py37h86efe34_0    conda-forge
importlib_metadata        1.5.0                    py37_0
intel-openmp              2019.4                      233
ipykernel                 5.1.4            py37h39e3cac_0
ipython                   7.12.0           py37h5ca1d4c_0
ipython_genutils          0.2.0                    py37_0
ipywidgets                7.5.1                      py_0
isl                       0.12.2                        1    anaconda
isort                     4.3.21                   py37_0
itsdangerous              1.1.0                    py37_0
jbig                      2.1                  h4d881f8_0
jdcal                     1.4.1                      py_0
jedi                      0.16.0                   py37_0
jinja2                    2.11.1                     py_0
joblib                    0.14.1                     py_0
jpeg                      9b                   he5867d9_2
json5                     0.9.1                      py_0
jsonschema                3.2.0                    py37_0
julia                     0.4.1                    pypi_0    pypi
jupyter                   1.0.0                    py37_7
jupyter_client            5.3.4                    py37_0
jupyter_console           6.1.0                      py_0
jupyter_core              4.6.1                    py37_0
jupyterlab                1.2.6              pyhf63ae98_0
jupyterlab_server         1.0.6                      py_0
kdcount                   0.3.29           py37h776bbcc_5    bccp
keyring                   21.1.0                   py37_0
kiwisolver                1.1.0            py37h0a44026_0
krb5                      1.17.1               hddcf347_0
kwant                     1.4.1                    pypi_0    pypi
lazy-object-proxy         1.4.3            py37h1de35cc_0
ld64                      274.2                h7c2db76_0
libarchive                3.3.3                h786848e_5
libcurl                   7.68.0               h051b688_0
libcxx                    4.0.1                h579ed51_0
libcxxabi                 4.0.1                hebd6815_0
libedit                   3.1.20181209         hb402a30_0
libffi                    3.2.1                h475c297_4
libgfortran               3.0.1                h93005f0_2
libiconv                  1.15                 hdd342a3_7
liblief                   0.9.0                h2a1bed3_2
libpng                    1.6.37               ha441bb4_0
libsodium                 1.0.16               h3efe00b_0
libssh2                   1.8.2                ha12b0ac_0
libtiff                   4.1.0                hcb84e12_0
libxml2                   2.9.9                hf6e021a_1
libxslt                   1.1.33               h33a18ac_0
ligo-segments             1.2.0                    pypi_0    pypi
llvm                      4.0.1                hc748206_0
llvm-lto-tapi             4.0.1                h6701bc3_0
llvm-openmp               4.0.1                hcfea43d_1
llvmlite                  0.31.0           py37h1341992_0
locket                    0.2.0                    py37_1
lscsoft-glue              2.0.0                    pypi_0    pypi
lxml                      4.5.0            py37hef8c89e_0
lz4-c                     1.8.1.2              h1de35cc_0
lzo                       2.10                 h362108e_2
mako                      1.1.0                    pypi_0    pypi
markupsafe                1.1.1            py37h1de35cc_0
matplotlib                3.1.3                    py37_0
matplotlib-base           3.1.3            py37h9aa3819_0
mccabe                    0.6.1                    py37_1
mcfit                     0.0.16           py37h5ca1d4c_1    bccp
mcint                     0.1.dev5                 pypi_0    pypi
mistune                   0.8.4            py37h1de35cc_0
mkl                       2019.4                      233
mkl-service               2.3.0            py37hfbe908c_0
mkl_fft                   1.0.15           py37h5e564d8_0
mkl_random                1.1.0            py37ha771720_0
more-itertools            8.2.0                      py_0
mpc                       1.1.0                h6ef4df4_1
mpfr                      4.0.1                h3018a27_3
mpi                       1.0                       mpich
mpi4py                    3.0.3            py37h77202c6_0
mpich                     3.3.2                hc856adb_0
mpld3                     0.3                      pypi_0    pypi
mpmath                    1.1.0                    py37_0
mpsort                    0.1.17           py37h62e6fb7_9    bccp
msgpack-python            0.6.1            py37h04f5b5a_1
multipledispatch          0.6.0                    py37_0
multiprocess              0.70.9                   pypi_0    pypi
navigator-updater         0.2.1                    py37_0
nbconvert                 5.6.1                    py37_0
nbformat                  5.0.4                      py_0
ncurses                   6.1                  h0a44026_1
networkx                  2.4                        py_0
nltk                      3.4.5                    py37_0
nose                      1.3.7                    py37_2
notebook                  6.0.3                    py37_0
numba                     0.48.0           py37h6c726b0_0
numexpr                   2.7.1            py37hce01a72_0
numpy                     1.17.4                   pypi_0    pypi
numpy-base                1.18.1           py37h6575580_1
numpydoc                  0.9.2                      py_0
olefile                   0.46                     py37_0
opencv-python             3.4.2.16                 pypi_0    pypi
openpyxl                  3.0.3                      py_0
openssl                   1.1.1g               h0b31af3_0    conda-forge
owslib                    0.19.2                     py_1    conda-forge
packaging                 20.1                       py_0
palettable                3.3.0                    pypi_0    pypi
pandas                    0.25.3           py37h0a44026_0
pandoc                    2.2.3.2                       0
pandocfilters             1.4.2                    py37_1
pango                     1.42.4               haa940fe_4    conda-forge
parso                     0.6.1                      py_0
partd                     1.1.0                      py_0
path                      13.1.0                   py37_0
path.py                   12.4.0                        0
pathlib2                  2.3.5                    py37_0
pathos                    0.2.5                    pypi_0    pypi
patsy                     0.5.1                    py37_0
pcre                      8.43                 h0a44026_0
pep8                      1.7.1                    py37_0
pexpect                   4.8.0                    py37_0
pfft-python               0.1.21          py37h62e6fb7_10    bccp
pickleshare               0.7.5                    py37_0
pillow                    7.0.0            py37h4655f20_0
pip                       19.3.1                   pypi_0    pypi
pixman                    0.38.0            h01d97ff_1003    conda-forge
pkginfo                   1.5.0.1                  py37_0
pluggy                    0.13.1                   py37_0
ply                       3.11                     py37_0
pmesh                     0.1.55           py37h776bbcc_5    bccp
powerbox                  0.6.0                    pypi_0    pypi
pox                       0.2.7                    pypi_0    pypi
ppft                      1.6.6.1                  pypi_0    pypi
progressbar               2.5                      pypi_0    pypi
proj4                     6.1.1                hca663eb_1    conda-forge
prometheus_client         0.7.1                      py_0
prompt_toolkit            3.0.3                      py_0
psrqpy                    1.0.0                    pypi_0    pypi
psutil                    5.6.7            py37h1de35cc_0
ptyprocess                0.6.0                    py37_0
py                        1.8.1                      py_0
py-lief                   0.9.0            py37h1413db1_2
pycbc                     1.15.1                   pypi_0    pypi
pycodestyle               2.5.0                    py37_0
pycosat                   0.6.3            py37h1de35cc_0
pycparser                 2.19                     py37_0
pycrypto                  2.6.1            py37h1de35cc_9
pycurl                    7.43.0.5         py37ha12b0ac_0
pyepsg                    0.4.0                      py_0    conda-forge
pyfftw                    0.11.1          py37h0aba3d0_1002    conda-forge
pyflakes                  2.1.1                    py37_0
pyflation                 0.2.3                    pypi_0    pypi
pygments                  2.5.2                      py_0
pykdtree                  1.3.1           py37h10e2902_1003    conda-forge
pylians3                  3.0                      pypi_0    pypi
pylint                    2.4.4                    py37_0
pyodbc                    4.0.30           py37h0a44026_0
pyopenssl                 19.1.0                   py37_0
pyparsing                 2.4.6                      py_0
pyproj                    2.3.1            py37h9bb365a_0    conda-forge
pyqt                      5.9.2            py37h655552a_2
pyrsistent                0.15.7           py37h1de35cc_0
pyshp                     2.1.0                      py_0    conda-forge
pysocks                   1.7.1                    py37_0
pytables                  3.4.4            py37h13cba08_0
pytest                    5.3.5                    py37_0
pytest-arraydiff          0.3              py37h39e3cac_0
pytest-astropy            0.8.0                      py_0
pytest-astropy-header     0.1.2                      py_0
pytest-doctestplus        0.5.0                      py_0
pytest-openfiles          0.4.0                      py_0
pytest-remotedata         0.3.2                    py37_0
pytest-runner             5.2                        py_0    conda-forge
python                    3.7.2                haf84260_0
python-dateutil           2.8.1                      py_0
python-libarchive-c       2.8                     py37_13
python-mimeparse          1.6.0                    pypi_0    pypi
python.app                2                        py37_8
python_abi                3.7                     1_cp37m    conda-forge
pytz                      2019.3                     py_0
pywavelets                1.1.1            py37h1de35cc_0
pyyaml                    5.2              py37h1de35cc_0
pyzmq                     18.1.1           py37h0a44026_0
qt                        5.9.7                h468cd18_1
qtawesome                 0.6.1                      py_0
qtconsole                 4.6.0                      py_1
qtpy                      1.9.0                      py_0
r-base                    3.4.3                h8d10ed9_4
r-maps                    3.2.0            r343h7f474d2_0
readline                  7.0                  h1de35cc_5
requests                  2.22.0                   py37_1
rope                      0.16.0                     py_0
ruamel_yaml               0.15.87          py37h1de35cc_0
runtests                  0.0.28                   py37_2    bccp
scikit-image              0.16.2           py37h6c726b0_0
scikit-learn              0.22.1           py37h27c97d8_0
scipy                     1.2.0                    pypi_0    pypi
seaborn                   0.10.0                     py_0
selenium                  3.141.0                  pypi_0    pypi
send2trash                1.5.0                    py37_0
setuptools                45.2.0                   py37_0
shapely                   1.6.4           py37h5c88e11_1006    conda-forge
simplegeneric             0.8.1                    py37_2
singledispatch            3.4.0.3                  py37_0
sip                       4.19.8           py37h0a44026_0
six                       1.14.0                   py37_0
snappy                    1.1.7                he62c110_3
snowballstemmer           2.0.0                      py_0
sortedcollections         1.1.2                    py37_0
sortedcontainers          2.1.0                    py37_0
soupsieve                 1.9.5                    py37_0
sphinx                    2.4.0                      py_0
sphinxcontrib             1.0                      py37_1
sphinxcontrib-applehelp   1.0.1                      py_0
sphinxcontrib-devhelp     1.0.1                      py_0
sphinxcontrib-htmlhelp    1.0.2                      py_0
sphinxcontrib-jsmath      1.0.1                      py_0
sphinxcontrib-qthelp      1.0.2                      py_0
sphinxcontrib-serializinghtml 1.1.3                      py_0
sphinxcontrib-websupport  1.2.0                      py_0
spyder                    3.3.6                    py37_0
spyder-kernels            0.5.2                    py37_0
sqlalchemy                1.3.13           py37h1de35cc_0
sqlite                    3.31.1               ha441bb4_0
sqlparse                  0.3.1                    pypi_0    pypi
statsmodels               0.11.0           py37h1de35cc_0
sympy                     1.5.1                    py37_0
tbb                       2020.0               h04f5b5a_0
tblib                     1.6.0                      py_0
terminado                 0.8.3                    py37_0
testpath                  0.4.4                      py_0
tinyarray                 1.2.1                    pypi_0    pypi
tk                        8.6.8                ha441bb4_0
tktable                   2.10                 h1de35cc_0
toolz                     0.10.0                     py_0
tornado                   6.0.3            py37h1de35cc_3
tqdm                      4.42.1                     py_0
traitlets                 4.3.3                    py37_0
triangle                  20170429                 pypi_0    pypi
txaio                     18.8.1                   pypi_0    pypi
unicodecsv                0.14.1                   py37_0
unixodbc                  2.3.7                h1de35cc_0
urllib3                   1.25.8                   py37_0
virtualenv                16.7.8                   pypi_0    pypi
vpnotebook                0.1.3                    pypi_0    pypi
vpython                   7.4.7                    pypi_0    pypi
wcwidth                   0.1.8                      py_0
webencodings              0.5.1                    py37_1
werkzeug                  1.0.0                      py_0
wheel                     0.34.2                   py37_0
widgetsnbextension        3.5.1                    py37_0
wrapt                     1.11.2           py37h1de35cc_0
wurlitzer                 2.0.0                    py37_0
xlrd                      1.2.0                    py37_0
xlsxwriter                1.2.7                      py_0
xlwings                   0.17.1                   py37_0
xlwt                      1.3.0                    py37_0
xz                        5.2.4                h1de35cc_4
yaml                      0.1.7                hc338f04_2
zeromq                    4.3.1                h0a44026_3
zict                      1.0.0                      py_0
zipp                      2.2.0                      py_0
zlib                      1.2.11               h1de35cc_3
zstd                      1.3.7                h5bba6e5_0
(base)

**Comment by andrea0292** [comment]
Dear Yu,

I solved the problem! Apparently the problem was with the Jupyter notebook I think, for some reason it sounds like it was trying to import two different installations of Python, or two different environments.

Thanks a lot for the availability anyway, you corde is amazing!

Best,

Andrea

**Comment by rainwoodman** [comment]
Glad you were able to figure it out! I am closing the issue then.
