### ISSUE TITLE
"The Multipoles of the BOSS DR12 Dataset" Cookbook not working

### ISSUE THREAD

**Issue by ash2223** [bccp/nbodykit#624]
Hello,

The example algorithm located in boss-dr12-data.ipynb, when run exactly how it's written, produces an error: "The_MPI_Comm_size() function was called before MPI_INIT was invoked. This is disallowed by the MPI standard. Your MPI job will now abort." I've attached a screenshot of the issue here. Could you let me know how to fix this? Thank you!
<img width="1066" alt="Screen Shot 2020-07-13 at 4 29 23 PM" src="https://user-images.githubusercontent.com/61329093/87364047-6a894980-c527-11ea-8531-d040ff54b81c.png">

-Adam

**Comment by rainwoodman** [comment]
Your anaconda appears to be very old. This error looks like you have two
versions of MPI installed in the same environment and they are mixed up.

I recommend try to run this again after getting a new Python3 based release
and install nbodykit from the bccp channel?

- Y

**Comment by ash2223** [comment]
Works now. Thank you so much!
