### ISSUE TITLE
finding the domain decomposition

### ISSUE THREAD

**Issue by mahdiqezlou** [bccp/nbodykit#626]
Hello,
I have generated a mesh from an MPI run on a catalogue. How can I figure out the domain decomposition used in generating that mesh ?  (Each rank corresponds to which part of the mesh, when we let the nbodykit to chose the domain by itself). 

I used `cat['Position']` to find min and max of the particles within each rank. With that I could find the domain for each rank except the rank 0 in which the `cat['Position']` spans the whole snapshot ( but the `mesh.compute()` is of a size smaller than `[Nmesh, Nmesh, Nmesh]` )

Thanks!

**Comment by rainwoodman** [comment]
In general the range of cat['Position'] on this rank is not related to the
domain on this rank. During compute we temporarily create 'ghost' particles
to the local mesh with layout.exchange. After the painting is done, we then
destroy those ghost particles.

The mesh geometry is stored with the 'real' field created by mesh.compute().

real = mesh.compute()

then
real.slices is the slices in the [Nmesh, Nmesh, Nmesh] this local mesh
correspond to.
and
real.x (https://github.com/rainwoodman/pmesh/blob/master/pmesh/pm.py#L246)
is a list of the coordinate of the local mesh points in 0, 1, 2 dimension.

There are also a few other attributes related to the geometry of the local
mesh, defined around the same place in the code.

You probably also want to check out the 'apply' functions that apply
transformations to the local field based on the location; they are easier
to use (and more memory efficient) than directly operating on the field and
coordinates.

- Yu

**Comment by mahdiqezlou** [comment]
Thank you Yu. It was all very useful !
