### ISSUE TITLE
SurveyData2PCF vs. CorrelationFunction - They don't agree.

### ISSUE THREAD

**Issue by Uendert** [bccp/nbodykit#633]
Hi all,

When one compare the restuls from the SurveyData2PCF vs. the CorrelationFunction, it doesn't seem to agree.

**Steps To Reproduce**
I've followed yours BOSS DR12 Dataset tutorial ([here](https://nbodykit.readthedocs.io/en/latest/cookbook/boss-dr12-data.html)), but then I computed the 2PCF using the `SurveyData2PCF` for the [galaxy_DR12v5_CMASS_North.fits.gz](https://data.sdss.org/sas/dr12/boss/lss/) and their random data random0_DR12v5_CMASS_North.fits.gz. Additionally, I computed the theoretical 2PCF using `CorrelationFunction`. The results from this can be found in this figure [xi.pdf](https://github.com/bccp/nbodykit/files/5075370/xi.pdf). As one can see, the blue dots (which is 2PCF from data) is much higher than the theoretical curves. It is true they might diverge due to galaxy bias, but still, they diverge too much. And even when bias is taken into account via linear kaiser (orange curve in the fig) the same behavior continues.      

It seems to me, it is something related to normalization or some unit issue. 
Any thought on how this mismach could be solved?

Thanks,
Uendert

ps: Does nbodykit support bootstrap of the 2PCF to acess error bar in their estimate? Similiarly to what is done in astropy.astroML  [here](http://www.astroml.org/user_guide/correlation_functions.html).

**Version**
```
import nbodykit; print(nbodykit, nbodykit.__version__);
<module 'nbodykit' from '/home/uendert/anaconda3/envs/nbodykit-env/lib/python3.7/site-packages/nbodykit/__init__.py'> 0.3.14
```

**Comment by rainwoodman** [comment]
I agree. The DR12 correlation function you got looked strangely high. I see you closed the issue. Did you sort it out? It would be nice if you share what have gone wrong for the record.

There is no bootstrap in nbodykit. Computing 'rigorous' statistical significance is a higher level (and and messier) logic that we do not usually include in nbodykit.

What I usually do is grouping the data into healpix/healpy pixels, and the do bootstrap by manipulating the pixel-ed data. The steps are rather standard. I can only find a rather cryptic python module of mine that does bootstraping (but not the grouping into 'straps' part):

https://github.com/rainwoodman/kdcount/blob/master/kdcount/bootstrap.py#L125
