### ISSUE TITLE
store shotnoise in power spectrum files even without --remove-shotnoise

### ISSUE THREAD

**Issue by rainwoodman** [bccp/nbodykit#65]
Currently without --remove-shotnoise the shotnoise is not properly stored in the file(0).

Shall we change this to always store the shotnoise regardless of removal -- actually, what about just deprecate --remove-shotnoise altogether since the shotnoise is always stored in the file?

@nickhand , what do you think?

**Comment by nickhand** [comment]
@rainwoodman, we should just deprecate this...we are already saving N1/N2 and box dimensions, so I think removing shot noise should just  be a post-processing step handled by the user.

**Comment by rainwoodman** [comment]
This is deprecated. I am closing it.
