### ISSUE TITLE
Issues running TaskManager on nbody-kit installation at NERSC

### ISSUE THREAD

**Issue by vmos1** [bccp/nbodykit#652]
**Describe the bug**
The goal is to compute the 3 point function for 3d images. My code can do it successfully for 1 file per core. However, I need to use multiple cores for a single computation, since it is slow.
For this I'm trying to use TaskManager as mentioned [here](https://nbodykit.readthedocs.io/en/latest/results/parallel.html?highlight=parallel).

When I use
`    with TaskManager(cpus_per_task=2, use_all_cpus=True) as tm:`

I get errors as described below.

**Steps To Reproduce**
I'm running the code using the NERSC installation of nbodykit
`source /global/common/software/m3035/conda-activate.sh 3.7`

The python code is [here](https://github.com/vmos1/cosmogan_pytorch/blob/master/code/modules_threeptfcn/compute_3pct_parallelize_single_img.py)
and the batch script is [here](https://github.com/vmos1/cosmogan_pytorch/blob/master/code/modules_threeptfcn/batch_getcorrs-test.sh)

**Actual behaviour**
I get the error: 

Traceback (most recent call last):
  File "/global/u1/v/vpa/project/jpt_notebooks/Cosmology/Cosmo_GAN/repositories/cosmogan_pytorch/code/modules_threeptfcn/compute_3pct_parallelize_single_img.py", line 182, in <module>
    with TaskManager(cpus_per_task=2, use_all_cpus=True) as tm:
  File "/dev/shm/local/lib/python3.7/site-packages/nbodykit/__init__.py", line 125, in wrapped
    return func(*args, **kwargs)
  File "/dev/shm/local/lib/python3.7/site-packages/nbodykit/batch.py", line 99, in __init__
    raise ValueError("need at least two processes to use a TaskManager")
ValueError: need at least two processes to use a TaskManager

**Expected behaviour**
The code works without the TaskManager additions. 

**Screenshots**

**Version**
<module 'nbodykit' from '/dev/shm/local/lib/python3.7/site-packages/nbodykit/__init__.py'> 0.3.15
(Installation at NERSC)

**Additional context**
I've tried locally installing nbody-kit in a conda environment, but it also gives the same error.

**Comment by rainwoodman** [comment]
I don't see the slurm script, but you are supposed to do srun -n 2 (or more) to address the "need at least two processes to use a TaskManager" error.

**Comment by vmos1** [comment]
I have it working now. Thanks!
