### ISSUE TITLE
Problem with painting to mesh if value has zero mean

### ISSUE THREAD

**Issue by susanpyne** [bccp/nbodykit#674]
I'd like some advice about painting values on a mesh.  I've followed the example in the documentation for painting the momentum field using to.mesh except that in my case I need an unweighted field (1+delta)V.

If V has zero mean then I find that the resulting power spectrum depends on the number of objects with an approximately sqrt(N) scaling - see plot. The 'all' sample has about 180K objects, and the other two cases are random sub-samples with 50K and 10K objects.
![image](https://user-images.githubusercontent.com/14234948/204876507-1f4a9fa9-acb5-46ee-ac2e-a25e9324470a.png)
(The plot shows the cross power spectrum between my V field and the overdensity field. It is not actually a physically meaningful spectrum as I've stripped out some detail while trying to debug this).
The problem does not occur if the value field has non-zero mean - in that case the power spectrum is the same for all sample sizes.
I've tried with different random realisations and always find that a smaller sample yields a higher power spectrum.
I guess there's some division by zero going on somewhere but can't see where.

**Comment by susanpyne** [comment]
In case this was missed, just wondered if I can get a response?

**Comment by rainwoodman** [comment]
Hi,

Sorry I missed your message earlier. I am not very experienced with
weighted field power spectrum , so I don’t have an Inuit ion whether the
sqrt N scaling you observed is expecte or not.

I do wonder if you have put the mass of particles to Mass(weight) and the
velocity to the Value column? That’s the way to compute a weighted average
painting. Where the mass is the weight and used to compute the 1+delta
part, and the velocity is used to compute the v part of your formula. I
recall this is illustrated in one of the examples.

In this “language “ the usual mass paining is where the value column is all
1s and the weight column is all identical values.

**Comment by susanpyne** [comment]
Thank you.  I'm not actually painting the momentum field, so I am not using the particle mass at all. I simply want to paint a  number-weighted set of values V onto the mesh. I put weight =1 (ie default) everywhere and value equal to my V.  If V does not have zero mean this seems to work fine.

I tried painting (1+V) - so non-zero mean - and then 'unwinding' this but didn't get sensible results and anyway don't think I should need to do this.

Any other suggestions would be much appreciated. Thanks again.

**Comment by susanpyne** [comment]
I've now realised this issue is just because my sample sizes are small compared with the mesh size, so I have many empty cells which add spurious values into the variance and hence power spectrum. More noticeable when the mean of the painted field is zero.
So this is not an nbodykit issue and can be closed.

**Comment by rainwoodman** [comment]
Glad you sorted this out. Thanks for the update!
