### ISSUE TITLE
not read in correct file in FITs format

### ISSUE THREAD

**Issue by Moctobers** [bccp/nbodykit#680]
Hi,

I recently encounter an issue reading files in FITs format:

```
from nbodykit.source.catalog import FITSCatalog

catalog = FITSCatalog("galaxy_DR12v5_CMASSLOWZTOT_North.fits")

print(catalog['RA'].compute()[:5])

array([-1.17748860e+027, -4.93766557e+127, -1.11378842e+132,
       -4.79078996e-098,  2.11681203e-058])

```
which is clearly not the correct values for the "RA" column.

I have run the same code under the same conda environment before and there was never any issue. I just tried to re-create the same environment and reinstall the package, however, the issue pertains. Any insights into this issue would be really helpful!

thanks!

**Comment by rainwoodman** [comment]
Could you dump the version of fitsio from your condo environment? This
looked like an endianness mismatch. It could be related to version of
fitsio and numpy — I don’t immediately recall if nbodykit tries to override
the endianness.


Yu

**Comment by Moctobers** [comment]
Hi,

I’ve tried to pip reinstalled the fitsio and the issue persists.

Interestingly, if I read in the catalog in the following way:

catalog = FITSFile("galaxy_DR12v5_CMASSLOWZTOT_North.fits”)[:]

print(catalog[‘RA’])

….

the output all reads normal.

I wonder what’s happening in between FITSFile and FITSCatalog…






On 26. Jul 2023, at 17:18, Yu Feng ***@***.***> wrote:

endianness

**Comment by Moctobers** [comment]
Just want to add that I re-installed the nbodykit on my local laptop (apple silicon M1), the computing helpdesk at my home institute also helped me to test for 3 different types of CPUs (AMD Rome and Milan, Intel Haswell). They all have the same problem in loading files with FITSCatalog.

**Comment by Moctobers** [comment]
there seems to be some incompatibility issue with numpy+scipy+dask. Using the following versions combination the file reading works again:

Name: numpy
Version: 1.22.4

Name: scipy
Version: 1.7.1

Name: dask
Version: 2023.5.0
