### ISSUE TITLE
& breaks command line parsing of power.py

### ISSUE THREAD

**Issue by rainwoodman** [bccp/nbodykit#7]
The choice of & as the optional argument prefix in input file names is inconvinient, since in bash & will end a command line and put the command to background.

It needs to be escaped with \& in bash. Maybe we want to use a non special character instead, '-' or '/'.

**Comment by nickhand** [comment]
Okay, I've reverting back to just using '-' rather than '&'...seems like a simplest option

Closed by 4e3380f
