### ISSUE TITLE
normalization of correlation function from power.py is off.

### ISSUE THREAD

**Issue by rainwoodman** [bccp/nbodykit#79]
The norm of correlation function from power.py contains a dimension of `L**3`. This traces back to the multiply by L**3 in compute_power_3d(). 

Do we want to enforce compute_power_3d always return the power in correct dimension? @nickhand

**Comment by nickhand** [comment]
I know we talked about this offline, but did anyone fix this @rainwoodman

**Comment by rainwoodman** [comment]
I will.

**Comment by rainwoodman** [comment]
Fixed
