### ISSUE TITLE
measure real and imaginary components of power spectrum

### ISSUE THREAD

**Issue by nickhand** [bccp/nbodykit#87]
for my velocity correlator measurements, I need to be able to measure the real and imaginary components of the power spectrum -- not sure the best way to do this, i.e., another flag to change the estimator or perhaps we always measure real + complex (complex will usually be zero)

The data fields are definitely real, which guarantees that the negative kz modes will simply be the complex conjugate of the positive frequency. We currently only compute the real part of the power spectrum, so we only need to multiply by a factor of 2. 

Things get more complicated if the power spectrum is purely imaginary, as in the case of  <delta v_parallel>, which will have mu^1 dependency. It's trivial to add another estimator for the imaginary part of the power spectrum from the two input fields: just do c1.imag*c2.real - c1.real*c2.imag

This would complicate the code more (for perhaps a unique use-case), but on the other hand, the generalization might actually make the code easier to understand.

Thoughts, @rainwoodman ?

**Comment by rainwoodman** [comment]
How could there be an imaginary power spectrum? The two signals are not real?

**Comment by rainwoodman** [comment]
Could you link me a paper doing velocity correlation?

**Comment by nickhand** [comment]
I think the fact that two fields are real only guarantees Hermitian symmetry, but not that the imaginary part is zero. The imaginary part has to be zero for auto-correlations due to symmetry but can be non-zero for cross-correlations, Pat's paper [here](http://arxiv.org/pdf/0907.5220v1.pdf) describes this for density cross-correlations. 

For these velocity correlations, P_01 = <delta v_parallel> is a dipole with mu dependence, which translates to a imaginary power spectrum. This is is Section 3.2 of [Zvonimir's paper](http://arxiv.org/pdf/1207.0839v2.pdf). If you look at equation 3.12, you can see that just from the continuity equation, you'll get that the power is imaginary in this case

**Comment by nickhand** [comment]
Now that the code can handle different transfer functions for the two fields, the simplest thing in this case might just be to multiply the velocity complex field by i, which effectively switches the real and imaginary components of the power spectrum....this is what I was (accidentally) doing before.

**Comment by rainwoodman** [comment]
Thanks for the links.

What about this 

- define P = c1^* \times c2; the imaginary part of P3d wasn't used before so we will just fill it with the correct imaginary part. The real part of P3d is intact.
- bincount needs to be replaced with a version that can do complex weights
- For symmetric==True, handle the complex part correctly.

**Comment by nickhand** [comment]
this seems like the most clear solution -- just track both real and complex.

``project_to_basis`` would then return a complex result, right? What's the best way to handle that in the output section? We could specify a flag for which components to save, output both to different files, or the same file?

**Comment by rainwoodman** [comment]
What about saving both into the same file? Each p column would just turn
into two adjacent columns. This would break the compatibility but seems to
be cleanest.

?

**Comment by nickhand** [comment]
Yeah, I think I agree. I'll take a look at implementing this. Do you agree with below?

1. we weight the 3d power spectrum by the Legendre polynomial using mu = k_los / k (no abs mag) 
2. for modes with kz != 0, we add to those modes:
  * if LOS = 'z', then add Legendre(-mu) * complex conjugate 
  * otherwise, just add Legendre(mu) * complex conjugate

and then when binning, determine the mu bin number using abs(mu)

**Comment by rainwoodman** [comment]
I am mostly confused about the weighting line 463 to 471. 
when s is complex, the x2 becomes the sum of (s + s^*) -- but wouldn't that mean the imaginary part is cancelled out?

**Comment by rainwoodman** [comment]
I see the conjugate would count into a different mu bin. So my last comment was wrong..

What about dealing with three chunks when symmetric==True, kz == 0, kz > 0 and kz < 0? This way seems like we do not need to branch on LOS.

**Comment by nickhand** [comment]
Yep, I agree that this is the case when mu is even, such that P(mu) = P(-mu), but if mu is odd then the real part cancels out and the imaginary part gets the factor of 2. 

Mu will always switch sign for the conjugate since k -> -k, so I think what we actually want to do is something like:

```
p = y3d[:,nonsingular]
weighted_y3d = legendre(ell)(mu) * p +  legendre(ell)(-mu) *p.conj()
```

which works out to 2x real + 0x imag if ell is even, and vice-versa for odd ell

**Comment by nickhand** [comment]
I think we can still bin in mu = [0, 1], as long as we keep track of the sign of mu for the legendre weighting. I have something preliminary coded up that appears to work. I'll run some more tests and put in a pull request for you to take a look .

**Comment by rainwoodman** [comment]
Sure.

**Comment by nickhand** [comment]
shall we close this?

**Comment by rainwoodman** [comment]
Yes. But be aware of commit 7258a92ba2c4 .
