### ISSUE TITLE
domain decomposition crash in pmesh when using power-parallel.py

### ISSUE THREAD

**Issue by nickhand** [bccp/nbodykit#93]
This is a weird bug I ran into when running power-parallel.py. It seems to depend on the total number of processors available, as I can change the number of cpus and avoid this. I would guess it has something to do with splitting the domain weirdly over the processors, but I haven't investigated much. It doesn't happen if I run with fewer than the maximum available number of processors.

```
  File "/dev/shm/local/lib/python2.7/site-packages/pmesh/particlemesh.py", line 205, in decompose
    layout = pm.decompose(position)
    transform=self.transform0)
  File "/dev/shm/local/lib/python2.7/site-packages/pmesh/domain.py", line 323, in decompose
    return default_paint(field, pm)
    sil[j, s] = self._digitize(tmp - smoothing, self.grid[j]) - 1
  File "/dev/shm/local/lib/python2.7/site-packages/pmesh/domain.py", line 251, in _digitize
    layout = pm.decompose(position)
    return numpy.digitize(data, bins)
ValueError: The bins must be monotonically increasing or decreasing
```

**Comment by rainwoodman** [comment]
Could you hack in the code to print  self.partition.i_edges before pm_decompose is called?

It does seem to be the i_edges are totally messed up. What is the size of the communicator?

**Comment by nickhand** [comment]
Yes, I'll investigate this some more and report back

**Comment by rainwoodman** [comment]
Thanks!

**Comment by nickhand** [comment]
Okay so, @rainwoodman, I was running with Nmesh = 1024 and 320 total CPUs and "3 nodes" , so the world comm was split into the worker sub-comms of sizes [107, 106, 106]. So, 106+106+107+1=320 since 1 cpu acts as the master CPU and send/receive tasks.

for the comm of size 107, the edges were: 

```
partition.i_edges = [array([   0, 1024]), array([   0,   10,   20,   30,   40,   50,   60,   70,   80,   90,  100,
        110,  120,  130,  140,  150,  160,  170,  180,  190,  200,  210,
        220,  230,  240,  250,  260,  270,  280,  290,  300,  310,  320,
        330,  340,  350,  360,  370,  380,  390,  400,  410,  420,  430,
        440,  450,  460,  470,  480,  490,  500,  510,  520,  530,  540,
        550,  560,  570,  580,  590,  600,  610,  620,  630,  640,  650,
        660,  670,  680,  690,  700,  710,  720,  730,  740,  750,  760,
        770,  780,  790,  800,  810,  820,  830,  840,  850,  860,  870,
        880,  890,  900,  910,  920,  930,  940,  950,  960,  970,  980,
        990, 1000, 1010, 1020,    0,    0,    0,    0, 1024]), array([   0, 1024])]
```

and the comm with size 106: 

```
partition.i_edges = [array([   0,  512, 1024]), array([   0,   20,   40,   60,   80,  100,  120,  140,  160,  180,  200,
        220,  240,  260,  280,  300,  320,  340,  360,  380,  400,  420,
        440,  460,  480,  500,  520,  540,  560,  580,  600,  620,  640,
        660,  680,  700,  720,  740,  760,  780,  800,  820,  840,  860,
        880,  900,  920,  940,  960,  980, 1000, 1020,    0, 1024]), array([   0, 1024])]
```

**Comment by rainwoodman** [comment]
I see. The problem has two folds. 

The first is 107 and 106 are quite prime. They do not divide 1024 so PFFT opted to use an uneven decomposition. It may run better if you allocation some extra node and start 3 * 120 + 1 ranks -- I haven't yet quite figured the decomposition logic in PFFT.

The second is there is a bug in pmesh or pfft-python when the "load" on a rank is zero.

There is a third bug even after the previous bug is fixed. For example the 106 job would become .... 1000, 1020, 1024, 1024 .... And it would still fail digitize's 'increasing' test. Let me see if there is a workaround..

**Comment by rainwoodman** [comment]
I've tagged a 0.1.3 version of pfft-python that worksaround the problem over empty loaded ranks. 
Also watch https://github.com/mpip/pfft/issues/22 on the upstream pfft status of the issue.

It turns out digitize does not require a strictly increasing list of bin edges even in 1.9.2 so the third concern doesn't seem to apply. 

Could  you try with the newer version of pfft-python?

**Comment by nickhand** [comment]
okay, the new version of pfft-python has fixed this issue

**Comment by rainwoodman** [comment]
Awesome. I will close this one.
