### ISSUE TITLE
Define a list of targets for v0.1.0.

### ISSUE THREAD

**Issue by rainwoodman** [bccp/nbodykit#98]

**Comment by nickhand** [comment]
@rainwoodman , what's left for v0.1? 

a few things that might be nice:
* a caching system to avoid repeated calculations? I'm thinking for painted fields, ffts, etc, but there are probably other nice uses. probably need to do this after #118. (this package [joblib](http://pythonhosted.org/joblib/) has some nice features...). Also, maybe something like memory caching to pass around outputs, (I'm thinking this would be useful for FoF output in the emulator pipeline)
* more general output plugins, specified like `DataSource` objects for algorithms. it's sort of the only thing that isn't implemented this way. Could be useful for grabbing output results at a memory address...

**Comment by rainwoodman** [comment]
- The automatic dependency tracking of joblib or just the dump interface? If it is just the dump interface we are better off using numpy.tofile. It is not very clear to me how to best make use of the dependency tracking of joblib -- decorating nbodykit functions doesn't seem to be the correct way of doing it.
- What is the the life cycle of a cache? How do we expire old caches? Do we need a new cache if the number of ranks changes?

- Output: Writing is always harder than reading. But it will be very messy, because each algorithm defines its own schema within a container format -- the situation is like an avi file can contain quicktime or mpeg format data streams, and we will end up with something as complicated as ffmpeg..  If we do want to make the output abstract, I would suggest DataSink as the name of the extension point. 

- Memory: We don't need output plugins for this. The 'run' function of algorithms returns results in memory. We just need some (maybe just one) new DataSource that takes input from in memory array.

**Comment by nickhand** [comment]
I'm going to close this, as we are now on v0.1.2 and have done all of the thing we want listed here
